### ISSUE TITLE
Passing memory allocated via `cudaMallocManaged()` to `write()` results in `EFAULT`

### ISSUE THREAD

**Issue by gimaker** [google/gvisor#10331]
### Description

Several of our customers ran in trouble during checkpointing when fine-tuning using [paged optimizers from bitsandbytes ](https://github.com/TimDettmers/bitsandbytes/blob/main/bitsandbytes/optim/optimizer.py) (e.g. `paged_adamw_8bit`). "Paged" in this case means they it uses `cudaMallocManaged()`. This works fine when not running in gVisor.

What this boils down to is that during checkpointing, pytorch will attempt to `write()` the `cudaMallocManaged()`-buffer directly, which results in getting an `EFAULT` from gVisor. We hit this code: https://github.com/google/gvisor/blob/1e1334e88f17efd04a4d0bd67cdd3f9dd3480320/pkg/sentry/devices/nvproxy/uvm_mmap.go#L84-L88

According to our customers this used to work, so this is a suspected but non-verified regression (also possible that this could have regressed due to a change in bitsandbytes or pytorch).

### Steps to reproduce

This Dockerfile works to repro the issue (tested on T4 - but we get the same issue on A10G and A100) using driver version `535.129.03`:

```
FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

COPY <<EOF uvm.cu
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <assert.h>

#define N 64*64

int main(){
  float *d_a;
  assert(cudaMallocManaged((void**)&d_a, sizeof(float) * N) == 0);
  assert(cudaMemset(d_a, 0, sizeof(float) * N) == 0);

  int fd = open("/out.txt", O_TRUNC | O_WRONLY | O_CREAT, 0644);
  if (fd == -1) {
    printf("failed open file: %s", strerror(errno));
    return -1;
  }
  int written = write(fd, d_a, sizeof(float) * N);
  if (written == -1) {
    printf("write failed with errno=%i: %s", errno, strerror(errno));
    return -1;
  }
  close(fd);

  cudaFree(d_a);
  return 0;
}
EOF

RUN nvcc /uvm.cu -o /uvm
CMD /uvm
```

-->

```
$ docker run --runtime=runsc-debug --gpus=all --rm sha256:dc5a68e4c4fa0355900aac12c48cc1fbe5ae58b314ed88643ea8bbc633a7ee2f

==========
== CUDA ==
==========

CUDA Version 12.4.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

write failed with errno=14: Bad address
```

This works when run outside of gVisor.

### runsc version

```shell
runsc version release-20240422.0
spec: 1.1.0-rc.1
```

### docker version (if using docker)

```shell
N/A - this is also reproducible when using runsc directly
```

### uname

`Linux staffan-gvisor-test 5.15.0-1053-gcp #61~20.04.1-Ubuntu SMP Mon Feb 26 16:50:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### runsc debug logs (if available)

Full debug logs: [runsc-debug.log](https://github.com/google/gvisor/files/15128206/runsc-debug.log)

Relevant excerpt:
```shell
I0426 09:13:13.456211    9540 strace.go:564] [  22:  22] uvm E munmap(0x7ea03c000000, 0x1fff000)
I0426 09:13:13.456225    9540 strace.go:602] [  22:  22] uvm X munmap(0x7ea03c000000, 0x1fff000) = 0 (0x0) (2.751µs)
I0426 09:13:13.456248    9540 strace.go:567] [  22:  22] uvm E getcpu(0x7ebd4a1dbe84, 0x0, 0x0)
I0426 09:13:13.456261    9540 strace.go:605] [  22:  22] uvm X getcpu(0x7ebd4a1dbe84, 0x0, 0x0) = 0 (0x0) (1.975µs)
I0426 09:13:13.456281    9540 strace.go:576] [  22:  22] uvm E mmap(0x7ea03a000000, 0x200000, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_FIXED, 0x9 /dev/nvidia-uvm, 0x7ea03a000000)
I0426 09:13:13.456338    9540 strace.go:614] [  22:  22] uvm X mmap(0x7ea03a000000, 0x200000, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_FIXED, 0x9 /dev/nvidia-uvm, 0x7ea03a000000) = 139226632945664 (0x7ea03a000000) (46.499µs)
I0426 09:13:13.456359    9540 strace.go:567] [  22:  22] uvm E ioctl(0x9 /dev/nvidia-uvm, 0x48, 0x7ebd4a1dbdd0)
D0426 09:13:13.456366    9540 uvm.go:135] [  22:  22] nvproxy: uvm ioctl 72 = 0x48
I0426 09:13:13.456380    9540 strace.go:605] [  22:  22] uvm X ioctl(0x9 /dev/nvidia-uvm, 0x48, 0x7ebd4a1dbdd0) = 0 (0x0) (13.723µs)
I0426 09:13:13.456407    9540 strace.go:567] [  22:  22] uvm E ioctl(0x9 /dev/nvidia-uvm, 0x2d, 0x7ebd4a1dbed0)
D0426 09:13:13.456414    9540 uvm.go:135] [  22:  22] nvproxy: uvm ioctl 45 = 0x2d
I0426 09:13:13.456426    9540 strace.go:605] [  22:  22] uvm X ioctl(0x9 /dev/nvidia-uvm, 0x2d, 0x7ebd4a1dbed0) = 0 (0x0) (11.774µs)
I0426 09:13:13.456742    9540 strace.go:570] [  22:  22] uvm E openat(AT_FDCWD /, 0x563224f3e083 /out.txt, O_WRONLY|O_CREAT|O_TRUNC, 0o644)
I0426 09:13:13.456801    9540 strace.go:608] [  22:  22] uvm X openat(AT_FDCWD /, 0x563224f3e083 /out.txt, O_WRONLY|O_CREAT|O_TRUNC, 0o644) = 34 (0x22) (44.924µs)
W0426 09:13:13.456940    9540 log.go:351] nvproxy: rejecting uvmFDMemmapFile.MapInternal:
goroutine 212 [running]:
gvisor.dev/gvisor/pkg/log.Stacks(0x0)
        pkg/log/log.go:319 +0x67
gvisor.dev/gvisor/pkg/log.Traceback({0x12fd3ad, 0x2e}, {0x0, 0x0, 0x0})
        pkg/log/log.go:350 +0x3b
gvisor.dev/gvisor/pkg/sentry/devices/nvproxy.(*uvmFDMemmapFile).MapInternal(0xc000000001?, {0xc000953008?, 0x151a398?}, {0x88?, 0xaa?, 0x30?})
        pkg/sentry/devices/nvproxy/uvm_mmap.go:86 +0x26
gvisor.dev/gvisor/pkg/sentry/mm.pmaIterator.getInternalMappingsLocked({0xc000726c08?, 0x0?})
        pkg/sentry/mm/pma.go:1024 +0x9d
gvisor.dev/gvisor/pkg/sentry/mm.(*MemoryManager).getPMAInternalMappingsLocked(0x1000001?, {0xc000726c08?, 0x151a398?}, {0xc00030aa88?, 0xc000805008?})
        pkg/sentry/mm/pma.go:829 +0x45
gvisor.dev/gvisor/pkg/sentry/mm.(*MemoryManager).withInternalMappings(0xc000953008, {0x151a398, 0xc00030aa88}, {0x41?, 0xc000433538?}, {0xb8?, 0xa3?, 0x41?}, 0x0, 0xc0004334f0)
        pkg/sentry/mm/io.go:552 +0x3ef
gvisor.dev/gvisor/pkg/sentry/mm.(*MemoryManager).CopyIn(0x0?, {0x151a398?, 0xc00030aa88?}, 0xc000433570?, {0xc0001de400?, 0x400?, 0x1083740?}, {0x1?, 0x79?})
        pkg/sentry/mm/io.go:164 +0xdf
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).CopyInBytes(0x10?, 0x7faad772f5b8?, {0xc0001de400?, 0xc000601808?, 0xc000943010?})
        pkg/sentry/kernel/task_usermem.go:57 +0x45
gvisor.dev/gvisor/pkg/sentry/strace.dump(0xc00030aa88, 0x7ea03a000000, 0x4000, 0x59f409?, 0xc0?)
        pkg/sentry/strace/strace.go:128 +0x8a
gvisor.dev/gvisor/pkg/sentry/strace.(*SyscallInfo).pre(0xc0004338b0, 0xc00030aa88, {{0x22}, {0x7ea03a000000}, {0x4000}, {0x1a4}, {0x0}, {0x0}}, 0x400)
        pkg/sentry/strace/strace.go:392 +0x2aa
gvisor.dev/gvisor/pkg/sentry/strace.(*SyscallInfo).printEnter(0xc0004338b0, 0xc00030aa88, {{0x22}, {0x7ea03a000000}, {0x4000}, {0x1a4}, {0x0}, {0x0}})
        pkg/sentry/strace/strace.go:555 +0x5c
gvisor.dev/gvisor/pkg/sentry/strace.SyscallMap.SyscallEnter(0x0?, 0xc00030aa88, 0x1, {{0x22}, {0x7ea03a000000}, {0x4000}, {0x1a4}, {0x0}, {0x0}}, 0x3)
        pkg/sentry/strace/strace.go:686 +0x1dd
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).executeSyscall(0xc00030aa88, 0x1, {{0x22}, {0x7ea03a000000}, {0x4000}, {0x1a4}, {0x0}, {0x0}})
        pkg/sentry/kernel/task_syscall.go:91 +0xbc
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallInvoke(0xc00030aa88, 0x1, {{0x22}, {0x7ea03a000000}, {0x4000}, {0x1a4}, {0x0}, {0x0}})
        pkg/sentry/kernel/task_syscall.go:323 +0x45
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallEnter(0xc00030aa88, 0x1, {{0x22}, {0x7ea03a000000}, {0x4000}, {0x1a4}, {0x0}, {0x0}})
        pkg/sentry/kernel/task_syscall.go:283 +0x65
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscall(0xc0007889c0?)
        pkg/sentry/kernel/task_syscall.go:258 +0x2a5
gvisor.dev/gvisor/pkg/sentry/kernel.(*runApp).execute(0xc000812010?, 0xc00030aa88)
        pkg/sentry/kernel/task_run.go:263 +0xef7
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).run(0xc00030aa88, 0x16)
        pkg/sentry/kernel/task_run.go:98 +0x1e2
created by gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).Start in goroutine 26
        pkg/sentry/kernel/task_start.go:393 +0xe5

I0426 09:13:13.456953    9540 strace.go:567] [  22:  22] uvm E write(0x22 /out.txt, 0x7ea03a000000 (error decoding string: bad address), 0x4000)
...
```

**Comment by nixprime** [comment]
This is the problem described by the third paragraph of https://github.com/google/gvisor/blob/master/g3doc/proposals/nvidia_driver_proxy.md#unified-virtual-memory-uvm, so (1) it shouldn't be an nvproxy regression (2) fixing it might take a bit. Fixing `write()` is relatively easier (since the sentry only needs to read the UVM memory, no writeback is involved) but presumably PyTorch will also `read()` into UVM memory when restoring the checkpoint...
