### ISSUE TITLE
Problem in building gvisor on ARM64

### ISSUE THREAD

**Issue by mhomidi** [google/gvisor#10634]
### Description

Hi,
When I try to build the program on an ARM machine, I got this error:
```
$ make build TARGETS=runsc DESTINATION=bin/ DOCKER_BUILD=false
--- BUILD runsc
Computing main repo mapping:
Loading:
Loading: 0 packages loaded
Analyzing: target //runsc:runsc (0 packages loaded, 0 targets configured)
Analyzing: target //runsc:runsc (0 packages loaded, 0 targets configured)
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
INFO: Analyzed target //runsc:runsc (1 packages loaded, 65 targets configured).
ERROR: /home/HwHiAiUser/Hadi/gvisor/pkg/sentry/platform/systrap/sysmsg/BUILD:31:11: Executing genrule //pkg/sentry/platform/systrap/sysmsg:sysmsg_lib failed: (Exit 127): bash failed: error executing Genrule command (from target //pkg/sentry/platform/systrap/sysmsg:sysmsg_lib) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/bin/bash: /usr/bin/x86_64-linux-gnu-gcc: No such file or directory
Target //runsc:runsc failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.532s, Critical Path: 0.36s
INFO: 194 processes: 194 internal.
ERROR: Build did NOT complete successfully
make: *** [Makefile:60: build] Error 1
```
Anybody has any idea? I am building the project on the main branch.
```
$ uname -a
Linux server180 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 14:03:41 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by EtiennePerot** [comment]
The output states that you are missing `/usr/bin/x86_64-linux-gnu-gcc`. You are building on ARM. So the problem is that bazel thinks you are on x86 and is trying to execute x86-only build instructions. I'm not sure how to change this but I'm assuming it's a bazel flag that would otherwise need to be passed.

Is there any reason why you are using `DOCKER_BUILD=false`? The default is to build within a Docker container because this removes a lot of these types of incompatibilities.

**Comment by mhomidi** [comment]
The issue is that when I do this I faced this issue with the ssl:
```
 make build TARGETS=runsc DESTINATION=bin/
--- TAG default
--- DOCKER BUILD
gvisor-builder-e81bc265-aarch64
sha256:af57188f0b1e7a11d4f8c73fb90597e3bb41fd01fd9339bf4e243173813414c1
--- DOCKER RUN
6521506a21ee21c3841df58fcb248201e751950b52d5f5a14029d7b7849706c8
--- BUILD runsc
Another command holds the client lock:
pid=3915134
owner=client
cwd=/home/HwHiAiUser/Hadi/gvisor

Waiting for it to complete...
Another command (pid=3915134) is running. Waiting for it to complete on the server (server_pid=3915171)...
Computing main repo mapping:
Computing main repo mapping:
Computing main repo mapping:
Computing main repo mapping:
Computing main repo mapping:
Computing main repo mapping:
Computing main repo mapping:
Computing main repo mapping:
WARNING: Download from https://github.com/googleapis/googleapis/archive/64926d52febbf298cb82a8f472ade4a3969ba922.zip failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
INFO: Repository googleapis instantiated at:
  /home/HwHiAiUser/Hadi/gvisor/WORKSPACE:63:13: in <toplevel>
Repository rule http_archive defined at:
  /home/HwHiAiUser/.cache/bazel/_bazel_HwHiAiUser/a1f8183f863677b9d2e5bb89a32296ae/external/bazel_tools/tools/build_defs/repo/http.bzl:369:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'googleapis':
   Traceback (most recent call last):
        File "/home/HwHiAiUser/.cache/bazel/_bazel_HwHiAiUser/a1f8183f863677b9d2e5bb89a32296ae/external/bazel_tools/tools/build_defs/repo/http.bzl", line 133, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/googleapis/googleapis/archive/64926d52febbf298cb82a8f472ade4a3969ba922.zip] to /home/HwHiAiUser/.cache/bazel/_bazel_HwHiAiUser/a1f8183f863677b9d2e5bb89a32296ae/external/googleapis/temp9736409282895601600/64926d52febbf298cb82a8f472ade4a3969ba922.zip: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: /home/HwHiAiUser/Hadi/gvisor/WORKSPACE:63:13: fetching http_archive rule //external:googleapis: Traceback (most recent call last):
        File "/home/HwHiAiUser/.cache/bazel/_bazel_HwHiAiUser/a1f8183f863677b9d2e5bb89a32296ae/external/bazel_tools/tools/build_defs/repo/http.bzl", line 133, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/googleapis/googleapis/archive/64926d52febbf298cb82a8f472ade4a3969ba922.zip] to /home/HwHiAiUser/.cache/bazel/_bazel_HwHiAiUser/a1f8183f863677b9d2e5bb89a32296ae/external/googleapis/temp9736409282895601600/64926d52febbf298cb82a8f472ade4a3969ba922.zip: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: Error computing the main repository mapping: no such package '@@googleapis//': java.io.IOException: Error downloading [https://github.com/googleapis/googleapis/archive/64926d52febbf298cb82a8f472ade4a3969ba922.zip] to /home/HwHiAiUser/.cache/bazel/_bazel_HwHiAiUser/a1f8183f863677b9d2e5bb89a32296ae/external/googleapis/temp9736409282895601600/64926d52febbf298cb82a8f472ade4a3969ba922.zip: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
make: *** [Makefile:60: build] Error 1
```
I also tried to solve this by using [this](https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ) but it did not work. 
Isn't there any way to disable SSL in bazel for building the project?

**Comment by mhomidi** [comment]
The issue is solved by following and running all command on `images/default/Dockerfile`.

**Comment by EtiennePerot** [comment]
Good that you got it figured out. It is weird that you'd get an SSL error though. Perhaps you are behind a firewall that tampers with SSL connections? This may be worked around by bind-mounting `/etc/ssl/certs` into the Docker build container. This is still safe to do even on man-in-the-middle'd SSL connections because all the build-time dependencies are checked against a hash after being downloaded.
