### ISSUE TITLE
Crash when running inside LXC container

### ISSUE THREAD

**Issue by alexpdp7** [google/gvisor#1499]
Hi,

I'm trying to run Docker containers using gvisor inside an LXC container (Proxmox). I have installed upstream Docker and the gvisor Debian packages using the apt repo.

When I try to start the `docker` service, I get the following in the logs:

```
Jan  3 10:47:56 debtest systemd[1]: Starting Docker Socket for the API.
Jan  3 10:47:56 debtest systemd[1]: Listening on Docker Socket for the API.
Jan  3 10:47:56 debtest modprobe[1306]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/5.3.13-1-pve/modules.dep.bin'
Jan  3 10:47:56 debtest modprobe[1306]: modprobe: FATAL: Module overlay not found in directory /lib/modules/5.3.13-1-pve
Jan  3 10:47:56 debtest systemd[1]: Started containerd container runtime.
Jan  3 10:47:56 debtest systemd[1]: Starting Docker Application Container Engine...
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.108483167Z" level=info msg="starting containerd" revision=b34a5c8af56e510852c35414db4c1f4fa6172339 version=1.2.10
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.109514404Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." type=io.containerd.content.v1
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.109711862Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." type=io.containerd.snapshotter.v1
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.110133257Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.110414475Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.aufs"..." type=io.containerd.snapshotter.v1
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.116447460Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.aufs" error="modprobe aufs failed: "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/5.3.13-1-pve/modules.dep.bin'\nmodprobe: FATAL: Module aufs not found in directory /lib/modules/5.3.13-1-pve\n": exit status 1"
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.116720685Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.116944078Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.117274833Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.117742503Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.zfs" error="exec: "zfs": executable file not found in $PATH: "zfs fs list -Hp -o name,origin,used,available,mountpoint,compression,type,volsize,quota,referenced,written,logicalused,usedbydataset rpool/data/subvol-100-disk-0" => "
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.117946212Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.118152771Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.118350183Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/5.3.13-1-pve/modules.dep.bin'\nmodprobe: FATAL: Module aufs not found in directory /lib/modules/5.3.13-1-pve\n": exit status 1"
Jan  3 10:47:56 debtest containerd[1308]: time="2020-01-03T10:47:56.118568009Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="exec: "zfs": executable file not found in $PATH: "zfs fs list -Hp -o name,origin,used,available,mountpoint,compression,type,volsize,quota,referenced,written,logicalused,usedbydataset rpool/data/subvol-100-disk-0" => "
Jan  3 10:47:56 debtest containerd[1308]: panic: invalid freelist page: 0, page type is unknown<00>
Jan  3 10:47:56 debtest containerd[1308]: goroutine 1 [running]:
Jan  3 10:47:56 debtest containerd[1308]: github.com/containerd/containerd/vendor/go.etcd.io/bbolt.(*freelist).read(0xc000238570, 0x7f0e14024000)
Jan  3 10:47:56 debtest containerd[1308]: #011/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/freelist.go:237 +0x2b9
Jan  3 10:47:56 debtest containerd[1308]: github.com/containerd/containerd/vendor/go.etcd.io/bbolt.(*DB).loadFreelist.func1()
Jan  3 10:47:56 debtest containerd[1308]: #011/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/db.go:292 +0x11e
Jan  3 10:47:56 debtest containerd[1308]: sync.(*Once).Do(0xc00000c328, 0xc0001fabb8)
Jan  3 10:47:56 debtest containerd[1308]: #011/usr/local/go/src/sync/once.go:44 +0xb5
Jan  3 10:47:56 debtest containerd[1308]: github.com/containerd/containerd/vendor/go.etcd.io/bbolt.(*DB).loadFreelist(0xc00000c1e0)
Jan  3 10:47:56 debtest containerd[1308]: #011/go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/db.go:285 +0x58
Jan  3 10:47:56 debtest containerd[1308]: github.com/containerd/containerd/vendor/go.etcd.io/bbolt.Open(0xc0001b9200, 0x3a, 0x5650000001a4, 0x56509b313840, 0xc000160e08, 0x1, 0x0)
Jan  3 10:47:56 debtest systemd[1]: containerd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan  3 10:47:56 debtest systemd[1]: containerd.service: Failed with result 'exit-code'.
Jan  3 10:47:56 debtest systemd[1]: docker.service: Main process exited, code=killed, status=15/TERM
Jan  3 10:47:56 debtest systemd[1]: docker.service: Succeeded.
Jan  3 10:47:56 debtest systemd[1]: Stopped Docker Application Container Engine.
Jan  3 10:47:56 debtest systemd[1]: docker.socket: Succeeded.
Jan  3 10:47:56 debtest systemd[1]: Closed Docker Socket for the API.
```

Feels like no storage plugin gets loaded and then panics? Perhaps it shouldn't panic?

Is there some storage driver that looks suitable for running inside an LXC container (even if performance might suck)? This is actually running on ZFS, but I doubt that's going to fly.

* The overlay module is actually loaded on the bare metal host
* Tried to install zfsutils-linux on the LXC container just for laughs, although it might not be such a terrible idea due to:

https://github.com/lxc/lxd/issues/4184#issuecomment-359184455

, but that just shuffles things around to:

```
Jan  3 11:03:05 debtest dockerd[531]: time="2020-01-03T11:03:05.045382259Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Jan  3 11:03:15 debtest containerd[530]: time="2020-01-03T11:03:15.019625355Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.zfs" error="exit status 1: "/sbin/zfs fs list -Hp -o name,origin,used,available,mountpoint,compression,type,volsize,quota,referenced,written,logicalused,usedbydataset rpool/data/subvol-100-disk-0" => /dev/zfs and /proc/self/mounts are required.
Jan  3 11:03:15 debtest containerd[530]: Try running 'udevadm trigger' and 'mount -t proc proc /proc' as root.
Jan  3 11:03:15 debtest containerd[530]: "
Jan  3 11:03:15 debtest containerd[530]: time="2020-01-03T11:03:15.019671671Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1
Jan  3 11:03:15 debtest containerd[530]: time="2020-01-03T11:03:15.019705563Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
Jan  3 11:03:15 debtest containerd[530]: time="2020-01-03T11:03:15.019716860Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/5.3.13-1-pve/modules.dep.bin'\nmodprobe: FATAL: Module aufs not found in directory /lib/modules/5.3.13-1-pve\n": exit status 1"
Jan  3 11:03:15 debtest containerd[530]: time="2020-01-03T11:03:15.019728612Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="exit status 1: "/sbin/zfs fs list -Hp -o name,origin,used,available,mountpoint,compression,type,volsize,quota,referenced,written,logicalused,usedbydataset rpool/data/subvol-100-disk-0" => /dev/zfs and /proc/self/mounts are required.
Jan  3 11:03:15 debtest containerd[530]: Try running 'udevadm trigger' and 'mount -t proc proc /proc' as root.
Jan  3 11:03:15 debtest containerd[530]: "
Jan  3 11:03:15 debtest containerd[530]: panic: invalid freelist page: 0, page type is unknown<00>
```

, which I suppose could be fixed to go farther than that, but doesn't sound healthy...

Other useful information to include is:

*   `runsc -v`

```
$ runsc --version
runsc version release-20191213.0
spec: 1.0.1-dev
```

*   `docker version` or `docker info` if more relevant

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```

*   `uname -a` - `git describe`

```
$ uname -a
Linux debtest 5.3.13-1-pve #1 SMP PVE 5.3.13-1 (Thu, 05 Dec 2019 07:18:14 +0100) x86_64 GNU/Linux
```

**Comment by alexpdp7** [comment]
Damn, this is a containerd issue, never mind
