### ISSUE TITLE
Runsc crash in share memory syscalls

### ISSUE THREAD

**Issue by zhuangel** [google/gvisor#1513]
We have encounter once sentry crash when running syzkaller test (share memory related case), here is the crash log.

```
panic: Incrementing non-positive ref count

goroutine 2314981 [running]:
gvisor.dev/gvisor/pkg/refs.(*AtomicRefCount).IncRef(...)
	pkg/refs/refcounter.go:374
gvisor.dev/gvisor/pkg/sentry/kernel/shm.(*Shm).ConfigureAttach(0xc01b7620e0, 0x1115ae0, 0xc0194a4a80, 0x20f65000, 0x100, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	pkg/sentry/kernel/shm/shm.go:507 +0x331
gvisor.dev/gvisor/pkg/sentry/syscalls/linux.Shmat(0xc0194a4a80, 0x398, 0x20f65000, 0x3000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	pkg/sentry/syscalls/linux/sys_shm.go:67 +0x11b
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).executeSyscall(0xc0194a4a80, 0x1e, 0x398, 0x20f65000, 0x3000, 0x0, 0x0, 0x0, 0x3f105afff700, 0xc0144dace8, ...)
	pkg/sentry/kernel/task_syscall.go:170 +0x125
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallInvoke(0xc0194a4a80, 0x1e, 0x398, 0x20f65000, 0x3000, 0x0, 0x0, 0x0, 0x0, 0x0)
	pkg/sentry/kernel/task_syscall.go:291 +0x66
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallEnter(0xc0194a4a80, 0x1e, 0x398, 0x20f65000, 0x3000, 0x0, 0x0, 0x0, 0x0, 0x0)
	pkg/sentry/kernel/task_syscall.go:252 +0x96
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscall(0xc0194a4a80, 0x2, 0xc01ee2a000)
	pkg/sentry/kernel/task_syscall.go:227 +0x139
gvisor.dev/gvisor/pkg/sentry/kernel.(*runApp).execute(0x0, 0xc0194a4a80, 0x10f59a0, 0x0)
	pkg/sentry/kernel/task_run.go:222 +0xf9d
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).run(0xc0194a4a80, 0x4737)
	pkg/sentry/kernel/task_run.go:92 +0x1bb
created by gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).Start
	pkg/sentry/kernel/task_start.go:311 +0xfe
```

I can't reproduce the issue with simple test case, from the crash stack, I guess the test case is running share memory related work, such as shmget/shmat/shmctl syscalls, after code analysis I found a probably logic could reproduce the crash, so I did some hack in Shm.ConfigureAttach and Shm.MarkDestroyed, run a simple share memory test case, the reproduce the same crash.

**Task1** [**shmget**]Create share memory segment A
           _[reference of segment is 0]_
**Task1** [**shmctl**]Destroy share memory segment A (before remove the key) [interrupted by **Task2**]
           _[reference of segment is 0]_
**Task2** [**shmget**]Find share memory segment A
           _[reference of segment is 0]_
**Task2** [**shmat**]Attach share memory segment A (before got segment lock) [interrupted by **Task1**]
           _[reference of segment is 0]_
**Task1** [**Continue**] Destroy share memory segment A
           _[reference of segment is -1]_
**Task2** [**Continue**] Attach share memory segment A
           **panic when increment the ref of segment**

**Comment by zhuangel** [comment]
Test case to reproduce the crash

```
#include <stddef.h>
#include <sys/shm.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>

int
main(int argc, char *argv[])
{
    int pid;
    int shmid;
    void *shm = NULL;

    pid = fork();
    if (pid == 0) {
        printf("Child sleep1 start\n");
        sleep(1);
        printf("Child sleep1 done\n");
        printf("Child process shmget\n");
        shmid = shmget((key_t)1234, 4096, 0666|IPC_CREAT);
        if (shmid == -1)
        {
            fprintf(stderr, "shmat failed\n");
            exit(EXIT_FAILURE);
        }
        printf("Child process shmget %d\n",shmid);
        printf("Child process shmat\n");
        shm = shmat(shmid, 0, 0);
        if (shm == (void *)-1)
        {
            fprintf(stderr, "shmat failed\n");
            exit(EXIT_FAILURE);
        }
        printf("Child process shmat 0x%x\n", shm);
        exit(EXIT_SUCCESS);
    }

    printf("Parent process shmget\n");
    shmid = shmget((key_t)1234, 4096, 0666|IPC_CREAT);
    if (shmid == -1)
    {
        fprintf(stderr, "shmat failed\n");
        exit(EXIT_FAILURE);
    }
    printf("Parent process shmget %d\n\n",shmid);
    printf("Parent sleep start\n");
    sleep(1);
    printf("Parent sleep done\n");
    printf("Parent shmctl IPC_RMID\n");
    if (shmctl(shmid, IPC_RMID, 0) == -1)
    {
        fprintf(stderr, "shmctl(IPC_RMID) failed %d\n",errno);
        exit(EXIT_FAILURE);
    }
    printf("Parent shmctl IPC_RMID %d\n",shmid);
    exit(EXIT_SUCCESS);
}

```

hack patch in sentry
```

--- a/pkg/sentry/kernel/shm/shm.go
+++ b/pkg/sentry/kernel/shm/shm.go
@@ -36,6 +36,7 @@ package shm
 import (
        "fmt"
        "sync"
+       "time"

        "gvisor.dev/gvisor/pkg/abi/linux"
        "gvisor.dev/gvisor/pkg/log"
@@ -400,6 +401,7 @@ func (s *Shm) InodeID() uint64 {
 //
 // Precondition: Caller must not hold s.mu.
 func (s *Shm) DecRef() {
+       log.Infof("DecRef enter %v",s)
        s.DecRefWithDestructor(s.destroy)
 }

@@ -488,9 +490,12 @@ type AttachOpts struct {
 // this once the map is installed. This reference prevents s from being
 // destroyed before the returned configuration is used.
 func (s *Shm) ConfigureAttach(ctx context.Context, addr usermem.Addr, opts AttachOpts) (memmap.MMapOpts, error) {
+       log.Infof("ConfigureAttach1 prepare")
+       time.Sleep(time.Second*5)
+       log.Infof("ConfigureAttach1 enter %v",s)
        s.mu.Lock()
        defer s.mu.Unlock()
        if s.pendingDestruction && s.ReadRefs() == 0 {
                return memmap.MMapOpts{}, syserror.EIDRM
        }

@@ -504,6 +509,9 @@ func (s *Shm) ConfigureAttach(ctx context.Context, addr usermem.Addr, opts Attac
                // in the user namespace that governs its IPC namespace." - man shmat(2)
                return memmap.MMapOpts{}, syserror.EACCES
        }
+       log.Infof("ConfigureAttach2 prepare")
+       time.Sleep(time.Second*25)
+       log.Infof("ConfigureAttach2 enter %v",s)
        s.IncRef()
        return memmap.MMapOpts{
                Length: s.size,
@@ -608,6 +616,7 @@ func (s *Shm) Set(ctx context.Context, ds *linux.ShmidDS) error {
 }

 func (s *Shm) destroy() {
+       log.Infof("DecRef-destroy enter %v",s)
        s.mfp.MemoryFile().DecRef(s.fr)
        s.registry.remove(s)
 }
@@ -617,6 +626,9 @@ func (s *Shm) destroy() {
 // times, and is safe to call after a segment has already been destroyed. See
 // shmctl(IPC_RMID).
 func (s *Shm) MarkDestroyed() {
+       log.Infof("MarkDestroyed prepare")
+       time.Sleep(time.Second*3)
+       log.Infof("MarkDestroyed enter %v",s)
        s.registry.dissociateKey(s)

        s.mu.Lock()
@@ -628,6 +640,9 @@ func (s *Shm) MarkDestroyed() {
        if !s.pendingDestruction {
                s.pendingDestruction = true
                s.mu.Unlock() // Must release s.mu before calling s.DecRef.
+               log.Infof("MarkDestroyed2 prepare")
+               time.Sleep(time.Second*10)
+               log.Infof("MarkDestroyed2 enter %v",s)
                s.DecRef()
                return
        }

```

**Comment by zhuangel** [comment]
A simple patch to fix the issue maybe change to strict check in ConfigureAttach, complex way maybe more refs when invoke related syscalls, such as shmat.

```
--- a/pkg/sentry/kernel/shm/shm.go
+++ b/pkg/sentry/kernel/shm/shm.go
@@ -490,7 +490,7 @@ type AttachOpts struct {
 func (s *Shm) ConfigureAttach(ctx context.Context, addr usermem.Addr, opts AttachOpts) (memmap.MMapOpts, error) {
        s.mu.Lock()
        defer s.mu.Unlock()
-       if s.pendingDestruction && s.ReadRefs() == 0 {
+       if s.pendingDestruction {
                return memmap.MMapOpts{}, syserror.EIDRM
        }

```

**Comment by prattmic** [comment]
Did you get this issue before or after https://github.com/google/gvisor/commit/6410387ff9b4f0dbe88325ea0e30776f5f3efd5d, which fixed a shm refcount issue?

**Comment by prattmic** [comment]
Based on the line numbers in the panic, it looks like this crash is from before https://github.com/google/gvisor/commit/6410387ff9b4f0dbe88325ea0e30776f5f3efd5d. Could you verify that the crash is no longer reproducible afterwards?

**Comment by zhuangel** [comment]
> Based on the line numbers in the panic, it looks like this crash is from before [6410387](https://github.com/google/gvisor/commit/6410387ff9b4f0dbe88325ea0e30776f5f3efd5d). Could you verify that the crash is no longer reproducible afterwards?

Great, in my hack case the issue can't be reproduced. as for syzkaller test we will continue running it.
But I think the current issue has been fixed by your patch, so I am going to close the issue.
