### ISSUE TITLE
java.nio.file.NoSuchFileException: /proc/sys/vm/max_map_count trying to run opendistro-es

### ISSUE THREAD

**Issue by NMFR** [google/gvisor#2337]
## Description

While trying to test an installation of open distro elasticsearch on Kubernetes using gVisor as the runtime i get the following error:

```
[2020-04-03T17:59:05,762][WARN ][o.e.b.BootstrapChecks    ] [opendistro-es-client-77d67f5955-dl58b] I/O exception while trying to read [/proc/sys/vm/max_map_count]
java.nio.file.NoSuchFileException: /proc/sys/vm/max_map_count
```

## Environment:
- Kubernetes v1.15.5
- containerd 1.2.13
- gVisor 20200323.0
- gvisor-containerd-shim v0.0.4

### Additional environment information:
```
$ runsc -version
runsc version release-20200323.0
spec: 1.0.1-dev
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ uname -a
Linux middleware-playground 5.0.0-1033-gcp #34-Ubuntu SMP Tue Mar 3 04:36:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## How to reproduce:

The starting point is a Kubernetes v1.15.5 cluster (in my case it is a single node cluster) and [containerd 1.2.13](https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.2.13.linux-amd64.tar.gz) container runtime. 

Install gVisor version 20200323.0:
```
(
    set -e
    TEMP_PATH=/tmp/gVisor
    VERSION=20200323.0
    URL=https://storage.googleapis.com/gvisor/releases/release/${VERSION}
    mkdir -p ${TEMP_PATH}
    cd ${TEMP_PATH}
    wget ${URL}/runsc -O ${TEMP_PATH}/runsc
    wget ${URL}/runsc.sha512 -O ${TEMP_PATH}/runsc.sha512
    sha512sum -c runsc.sha512
    sudo chown root:root ${TEMP_PATH}/runsc
    sudo chmod 0755 ${TEMP_PATH}/runsc
    sudo mv runsc /usr/local/bin
    cd ~
    rm -Rf ${TEMP_PATH}
)
```

Install and configure gvisor-containerd-shim v0.0.4:
```
(
    set -e
    TEMP_PATH=/tmp/gvisor-containerd-shim
    VERSION=v0.0.4
    URL=https://github.com/google/gvisor-containerd-shim/releases/download/${VERSION}/gvisor-containerd-shim.linux-amd64
    mkdir -p ${TEMP_PATH}
    cd ${TEMP_PATH}
    wget ${URL} -O ${TEMP_PATH}/gvisor-containerd-shim
    sudo chown root:root ${TEMP_PATH}/gvisor-containerd-shim
    sudo chmod 0755 ${TEMP_PATH}/gvisor-containerd-shim
    sudo mv gvisor-containerd-shim /usr/local/bin
{ # Add gvisor-containerd-shim configuration
cat <<EOF | sudo tee /etc/containerd/gvisor-containerd-shim.toml
# This is the path to the default runc containerd-shim.
runc_shim = "/usr/bin/containerd-shim"
EOF
}
    cd ~
    rm -Rf ${TEMP_PATH}
)
```

Note that your location of containerd-shim might be different, run `whereis containerd-shim` to get the binary’s path.

Configure the containerd CRI gVisor runtime handler:
```
(
    sudo mkdir -p /run/containerd/runsc
{ # Add gvisor-containerd-shim to containerd config.toml
cat <<EOF | sudo tee -a /etc/containerd/config.toml
disabled_plugins = ["restart"]
[plugins.linux]
  shim = "/usr/local/bin/gvisor-containerd-shim"
  shim_debug = true
[plugins.cri.containerd.runtimes.runsc]
  runtime_type = "io.containerd.runtime.v1.linux"
  runtime_engine = "/usr/local/bin/runsc"
  runtime_root = "/run/containerd/runsc"
EOF
}
    sudo systemctl restart containerd
)
```
Note that any configuration keys that are already present in the /etc/containerd/config.toml configuration file must be replaced and not duplicated.

Create the Kubernetes gVisor Runtime Class:
```
{ 
cat <<EOF | kubectl apply -f -
apiVersion: node.k8s.io/v1beta1
kind: RuntimeClass
metadata:
  name: gvisor
handler: runsc
EOF
}
```

Install helm v3.1.2:
```
(
    set -e
    TEMP_PATH=/tmp/helm
    VERSION=v3.1.2
    URL=https://get.helm.sh/helm-${VERSION}-linux-amd64.tar.gz
    mkdir -p ${TEMP_PATH}
    cd ${TEMP_PATH}
    wget ${URL} -O ${TEMP_PATH}/helm.tar.gz
    tar -zxvf ${TEMP_PATH}/helm.tar.gz
    sudo mv ${TEMP_PATH}/linux-amd64/helm /usr/local/bin/helm
    cd ~
    rm -Rf ${TEMP_PATH}
)
```

Install opendistro elasticsearch 7.6.1:
```
(
    set -e
    TEMP_PATH=/tmp/opendistro-for-elasticsearch
    mkdir -p ${TEMP_PATH}
    cd ${TEMP_PATH}   
    git clone https://github.com/opendistro-for-elasticsearch/opendistro-build
    cd ${TEMP_PATH}/opendistro-build/
    git checkout 31ff02f69fce1cbd08d03fead4293333646cb4f2
    cd ${TEMP_PATH}/opendistro-build/helm/opendistro-es/
    helm package .
    helm install opendistro-es opendistro-es-1.6.0.tgz --atomic --set kibana.enabled=false --set elasticsearch.data.persistence.storageClass=slow --set elasticsearch.master.persistence.storageClass=slow
    kubectl patch deploy opendistro-es-client --patch '{"spec":{"template": {"spec":{"runtimeClassName": "gvisor"}}}}'
    kubectl patch statefulset opendistro-es-data --patch '{"spec":{"template": {"spec":{"runtimeClassName": "gvisor"}}}}'
    kubectl patch statefulset opendistro-es-master --patch '{"spec":{"template": {"spec":{"runtimeClassName": "gvisor"}}}}'
    cd ~
    rm -Rf ${TEMP_PATH}
)
``` 

Check logs of the opendistro-es pods, they will be throwing the error right after they initialize:
```
[2020-04-03T17:59:03,289][INFO ][o.e.n.Node               ] [opendistro-es-client-77d67f5955-dl58b] initialized
[2020-04-03T17:59:03,290][INFO ][o.e.n.Node               ] [opendistro-es-client-77d67f5955-dl58b] starting ...
[2020-04-03T17:59:04,153][INFO ][o.e.t.TransportService   ] [opendistro-es-client-77d67f5955-dl58b] publish_address {10.217.0.145:9300}, bound_addresses {[::]:9300}
[2020-04-03T17:59:04,706][INFO ][c.a.o.e.p.c.ScheduledMetricCollectorsExecutor] [opendistro-es-client-77d67f5955-dl58b] Collector NetworkE2ECollector is still in progress, so skipping this Interval
[2020-04-03T17:59:04,713][INFO ][c.a.o.e.p.c.ScheduledMetricCollectorsExecutor] [opendistro-es-client-77d67f5955-dl58b] Collector OSMetrics is still in progress, so skipping this Interval
[2020-04-03T17:59:04,713][INFO ][c.a.o.e.p.c.ScheduledMetricCollectorsExecutor] [opendistro-es-client-77d67f5955-dl58b] Collector HeapMetrics is still in progress, so skipping this Interval
[2020-04-03T17:59:04,713][INFO ][c.a.o.e.p.c.ScheduledMetricCollectorsExecutor] [opendistro-es-client-77d67f5955-dl58b] Collector ThreadPoolMetrics is still in progress, so skipping this Interval
[2020-04-03T17:59:04,713][INFO ][c.a.o.e.p.c.ScheduledMetricCollectorsExecutor] [opendistro-es-client-77d67f5955-dl58b] Collector CircuitBreaker is still in progress, so skipping this Interval
[2020-04-03T17:59:04,714][INFO ][c.a.o.e.p.c.ScheduledMetricCollectorsExecutor] [opendistro-es-client-77d67f5955-dl58b] Collector DisksCollector is still in progress, so skipping this Interval
[2020-04-03T17:59:05,707][INFO ][c.a.o.e.p.c.ScheduledMetricCollectorsExecutor] [opendistro-es-client-77d67f5955-dl58b] Collector OSMetrics is still in progress, so skipping this Interval
[2020-04-03T17:59:05,748][INFO ][o.e.b.BootstrapChecks    ] [opendistro-es-client-77d67f5955-dl58b] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2020-04-03T17:59:05,762][WARN ][o.e.b.BootstrapChecks    ] [opendistro-es-client-77d67f5955-dl58b] I/O exception while trying to read [/proc/sys/vm/max_map_count]
java.nio.file.NoSuchFileException: /proc/sys/vm/max_map_count
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:373) ~[?:?]
```

**Comment by fvoznika** [comment]
gVisor does have `max_map_count` in procfs right now, but it should be easy to add.
@nixprime does gVisor MM have this limit anywhere?

**Comment by fvoznika** [comment]
You can path #2340 and try again to see if it fixes the problem.
