### ISSUE TITLE
arm64: build fails with SIGILL in GetASIDBits()

### ISSUE THREAD

**Issue by abliss** [google/gvisor#2778]
When I try to build with bazel on my arm64 machine, I fail with a SIGILL in GetASIDBits:
```

ERROR: /home/abliss/proj/gvisor/pkg/sentry/platform/ring0/BUILD:50:1: Executing genrule //pkg/sentry/platform/ring0:entry_impl_arm64 failed (Exit 2) process-wrapper failed: error executing command 
  (cd /home/abliss/.cache/bazel/_bazel_abliss/11a015252d6bf602b13102f8e3d1f029/sandbox/processwrapper-sandbox/32/execroot/__main__ && \
  exec env - \
    PATH=/home/abliss/.local/bin:/sbin:/usr/sbin:/usr/local/sbin:/home/abliss/bin:/home/abliss/.local/bin:/sbin:/usr/sbin:/usr/local/sbin:/home/abliss/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/abliss/tools/go/bin:/home/abliss/.meteor:/home/abliss/tools/go/bin:/home/abliss/.meteor \
    TMPDIR=/tmp \
  /home/abliss/.cache/bazel/_bazel_abliss/install/313d895418aec26168ff71eea0c8ba83/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; (echo -e '\''// build +arm64\n'\'' && bazel-out/host/bin/pkg/sentry/platform/ring0/gen_offsets/linux_arm64_stripped/gen_offsets && cat pkg/sentry/platform/ring0/entry_arm64.s) > bazel-out/aarch64-fastbuild/bin/pkg/sentry/platform/ring0/entry_impl_arm64.s')
SIGILL: illegal instruction
PC=0x145390 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
gvisor.dev/gvisor/pkg/sentry/platform/ring0/pagetables.GetASIDBits()
	pkg/sentry/platform/ring0/pagetables/pcids_aarch64.s:30 fp=0x4000066ed0 sp=0x4000066ed0 pc=0x145390
gvisor.dev/gvisor/pkg/sentry/platform/ring0/pagetables.init.0()
	pkg/sentry/platform/ring0/pagetables/pcids_aarch64.go:31 +0x20 fp=0x4000066ef0 sp=0x4000066ed0 pc=0x143540
runtime.doInit(0x301aa0)
	GOROOT/src/runtime/proc.go:5414 +0x9c fp=0x4000066f30 sp=0x4000066ef0 pc=0x4ee1c
runtime.doInit(0x303280)
	GOROOT/src/runtime/proc.go:5409 +0x58 fp=0x4000066f70 sp=0x4000066f30 pc=0x4edd8
runtime.main()
	GOROOT/src/runtime/proc.go:190 +0x1e0 fp=0x4000066fd0 sp=0x4000066f70 pc=0x42150
runtime.goexit()
	GOROOT/src/runtime/asm_arm64.s:1148 +0x4 fp=0x4000066fd0 sp=0x4000066fd0 pc=0x6bfd4

r0      0x301aa0
r1      0x4000066380
r2      0x4000066ef0
r3      0x400013e728
r4      0x4000066de8
r5      0x10
r6      0x1ee4c0
r7      0x1a6900
r8      0x4000066df8
r9      0x400013e738
r10     0x4
r11     0x0
r12     0xd
r13     0x1
r14     0x400013e700
r15     0x4000066c68
r16     0x4
r17     0xc8
r18     0x0
r19     0x190
r20     0x4000066e88
r21     0x4000114560
r22     0x4000002000
r23     0x0
r24     0x0
r25     0x0
r26     0x301ac8
r27     0x343a40
r28     0x4000000180
r29     0x4000066ec8
lr      0x143540
sp      0x4000066ed0
pc      0x145390
fault   0x0
```

```
$ uname -a
Linux localhost 3.18.41+ #3 SMP PREEMPT Wed Sep 5 23:45:56 EDT 2018 aarch64 aarch64 aarch64 GNU/Linux
$ cat /proc/cpuinfo
Processor   : AArch64 Processor rev 4 (aarch64)                                                                                                                       
processor   : 0                                                                                                                                                       
model name  : AArch64 Processor rev 4 (aarch64)                                                                                                                       
BogoMIPS    : 26.00                                                                                                                                                   
BogoMIPS    : 26.00                                                                                                                                                   
Features    : fp asimd evtstrm aes pmull sha1 sha2 crc32                                                                                                              
CPU implementer : 0x41                                                                                                                                                
CPU architecture: 8                                                                                                                                                   
CPU variant : 0x0                                                                                                                                                     
CPU part    : 0xd03                                                                                                                                                   
CPU revision    : 4          
...
Hardware    : MT6797X
```

As a workaround, I edited the assembly in `pcids_aarch64.s` to always return 8, and the build continued. (I personally have no idea whether 8 or 16 is the right answer for my system though.)

**Comment by amscanne** [comment]
@lubinszARM Looks like on some variants of ARM the GetASIDBits function can cause a SIGILL? Maybe an easy fix?

**Comment by lubinszARM** [comment]
Let me check it @amscanne @abliss 
Thanks for using Arm :)
