### ISSUE TITLE
VFS2: error fetching repositories running `bazel build //runsc:runsc`

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#3357]
Repro:
```
git clone https://github.com/google/gvisor.git /tmp/gvisor
docker run --rm --runtime=runsc-vfs2 -v /tmp/gvisor:/src -w /src l.gcr.io/google/bazel build //runsc:runsc
```

Error:
```
ERROR: An error occurred during the fetch of repository 'rules_python':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
		_clone_or_update(ctx)
	File "/root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
		fetch(ctx, git_repo)
	File "/root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 129, in fetch
		_git_maybe_shallow(ctx, <5 more arguments>)
	File "/root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 171, in _git_maybe_shallow
		_error(ctx.name, <2 more arguments>)
	File "/root/.cache/bazel/_bazel_root/f8087e59fd95af1ae29e8fcb7ff1a3dc/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(<1 more arguments>)
error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @rules_python:
fatal: bad object a7544d9e205e9df0fe2392bf3b0accd43fc8f386
error: https://github.com/bazelbuild/rules_python.git did not send all necessary objects
```

**Comment by ayushr2** [comment]
Looks like this has been fixed. Most likely #3395 was the fix. (as it fixed a similar issue too)
