### ISSUE TITLE
fuse: Closing an unmounted /dev/fuse fd crashes runsc-sandbox

### ISSUE THREAD

**Issue by jmillikin-stripe** [google/gvisor#3652]
**Description**

The following program, when run under `runsc --vfs2 --fuse`, will crash the sandbox:
```c
#include <fcntl.h>
#include <unistd.h>
int main() {
  int fd = open("/dev/fuse", O_RDWR);
  if (fd >= 0) {
    close(fd);
  }
  return 0;
}
```

Some added logging shows that `(*fuse.DeviceFD).Release` doesn't gracefully handle an incompletely constructed FUSE filesystem, for example if the `mount()` call failed:
```
I0818 01:39:32.890183   77348 dev.go:103] fuse.DeviceFD.Release: fd = 0xc00022a200
I0818 01:39:32.890215   77348 dev.go:104] fuse.DeviceFD.Release: fd.fs = 0x0
```

**Steps to reproduce**

Build the above C program and run it in a FUSE-enabled gVisor.

**Environment**

Using current master HEAD (988ab27058829fd2ccb550560a7651511d7b872a).

Relevant snippet from logs:
```
I0818 01:39:31.326740   77348 loader.go:153] [  82] Error opening /usr/local/bin/bash: no such file or directory
I0818 01:39:31.326814   77348 loader.go:153] [  82] Error opening /usr/sbin/bash: no such file or directory
I0818 01:39:31.326883   77348 loader.go:153] [  82] Error opening /usr/bin/bash: no such file or directory
I0818 01:39:31.326959   77348 loader.go:153] [  82] Error opening /sbin/bash: no such file or directory
I0818 01:39:32.890183   77348 dev.go:103] fuse.DeviceFD.Release: fd = 0xc00022a200
I0818 01:39:32.890215   77348 dev.go:104] fuse.DeviceFD.Release: fd.fs = 0x0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0xce0e83]

goroutine 825 [running]:
panic(0xedc4a0, 0x19eb850)
  GOROOT/src/runtime/panic.go:1064 +0x46d fp=0xc000399930 sp=0xc000399878 pc=0x43438d
runtime.panicmem(...)
  GOROOT/src/runtime/panic.go:212
runtime.sigpanic()
  GOROOT/src/runtime/signal_unix.go:695 +0x3da fp=0xc000399960 sp=0xc000399930 pc=0x44b8fa
gvisor.dev/gvisor/pkg/sentry/fsimpl/fuse.(*DeviceFD).Release(0xc00022a200, 0x12074c0, 0xc0004da000)
  pkg/sentry/fsimpl/fuse/dev.go:105 +0x113 fp=0xc000399998 sp=0xc000399960 pc=0xce0e83
gvisor.dev/gvisor/pkg/sentry/vfs.(*FileDescription).DecRef(0xc00022a200, 0x12074c0, 0xc0004da000)
  pkg/sentry/vfs/file_description.go:199 +0x228 fp=0xc000399a70 sp=0xc000399998 pc=0x6a93b8
gvisor.dev/gvisor/pkg/sentry/syscalls/linux/vfs2.Close(0xc0004da000, 0x3, 0x2, 0x7f2e1816e738, 0x690, 0x400610, 0x7f9825c10af0, 0x0, 0x0, 0x0, ...)
  pkg/sentry/syscalls/linux/vfs2/fd.go:44 +0x1a7 fp=0xc000399b08 sp=0xc000399a70 pc=0xbf40a7
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).executeSyscall(0xc0004da000, 0x3, 0x3, 0x2, 0x7f2e1816e738, 0x690, 0x400610, 0x7f9825c10af0, 0x0, 0x103a7e0, ...)
  pkg/sentry/kernel/task_syscall.go:170 +0x122 fp=0xc000399c68 sp=0xc000399b08 pc=0x8bd782
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallInvoke(0xc0004da000, 0x3, 0x3, 0x2, 0x7f2e1816e738, 0x690, 0x400610, 0x7f9825c10af0, 0x400610, 0x7f9825c10af0)
  pkg/sentry/kernel/task_syscall.go:305 +0x66 fp=0xc000399cf0 sp=0xc000399c68 pc=0x8be966
```

**Comment by ianlewis** [comment]
G'day @jmillikin-stripe! If you have a sec to post a short description of what you are thinking of using fuse for, either here, or in the [Gitter chat](https://gitter.im/gvisor/community), it would be most helpful as input for our planning.

**Comment by jmillikin-stripe** [comment]
(responded on Gitter)

**Comment by ayushr2** [comment]
I think this was fixed in https://github.com/google/gvisor/commit/ae59e529791e4763aaa25eee818605f17699fc67. Please reopen if you can still repro.
