### ISSUE TITLE
fuse: Stat() with FileDescription struct will panic

### ISSUE THREAD

**Issue by craig08** [google/gvisor#3655]
The `fileDescription` struct is introduced in FUSE_OPEN (#3174). If `Stat()` is called on a `fileDescription` struct then it will crash. Implement `vfs.DentryMetadataFileDescriptionImpl.Stat()` for `fileDescription` struct.
```
panic: illegal call to DentryMetadataFileDescriptionImpl.Stat

goroutine 85 [running]:
panic(0xe8e0c0, 0x11cd900)
        GOROOT/src/runtime/panic.go:1064 +0x46d fp=0xc000171510 sp=0xc000171458 pc=0x43438d
gvisor.dev/gvisor/pkg/sentry/vfs.DentryMetadataFileDescriptionImpl.Stat(0x120e6a0, 0xc0004b4000, 0x7ff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        pkg/sentry/vfs/file_description_impl_util.go:199 +0x58 fp=0xc000171530 sp=0xc000171510 pc=0x6ad198
gvisor.dev/gvisor/pkg/sentry/fsimpl/fuse.(*fileDescription).Stat(0xc0006c8680, 0x120e6a0, 0xc0004b4000, 0x7ff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        <autogenerated>:1 +0x9f fp=0xc000171688 sp=0xc000171530 pc=0xcec9ef
gvisor.dev/gvisor/pkg/sentry/vfs.(*FileDescription).Stat(0xc0006c8680, 0x120e6a0, 0xc0004b4000, 0x7ff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        pkg/sentry/vfs/file_description.go:534 +0x2c0 fp=0xc0001718e8 sp=0xc000171688 pc=0x6aa7d0
gvisor.dev/gvisor/pkg/sentry/syscalls/linux/vfs2.Fstat(0xc0004b4000, 0x3, 0x7f90728b3820, 0x7f90728b3820, 0x0, 0xf, 0x5649f8a5f500, 0x0, 0x0, 0x0, ...)
        pkg/sentry/syscalls/linux/vfs2/stat.go:137 +0x10d fp=0xc000171b08 sp=0xc0001718e8 pc=0xc1524d
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).executeSyscall(0xc0004b4000, 0x5, 0x3, 0x7f90728b3820, 0x7f90728b3820, 0x0, 0xf, 0x5649f8a5f500, 0x0, 0x1041520, ...)
        pkg/sentry/kernel/task_syscall.go:170 +0x122 fp=0xc000171c68 sp=0xc000171b08 pc=0x8bf3e2
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallInvoke(0xc0004b4000, 0x5, 0x3, 0x7f90728b3820, 0x7f90728b3820, 0x0, 0xf, 0x5649f8a5f500, 0xf, 0x5649f8a5f500)
        pkg/sentry/kernel/task_syscall.go:305 +0x66 fp=0xc000171cf0 sp=0xc000171c68 pc=0x8c05c6
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallEnter(0xc0004b4000, 0x5, 0x3, 0x7f90728b3820, 0x7f90728b3820, 0x0, 0xf, 0x5649f8a5f500, 0x11e1601, 0x100000000000000)
        pkg/sentry/kernel/task_syscall.go:265 +0x96 fp=0xc000171d50 sp=0xc000171cf0 pc=0x8c0156
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscall(0xc0004b4000, 0x2, 0xc0004b4000)
        pkg/sentry/kernel/task_syscall.go:240 +0x15c fp=0xc000171e10 sp=0xc000171d50 pc=0x8bfaec
gvisor.dev/gvisor/pkg/sentry/kernel.(*runApp).execute(0x0, 0xc0004b4000, 0x11e16a0, 0x0)
        pkg/sentry/kernel/task_run.go:274 +0xc18 fp=0xc000171f60 sp=0xc000171e10 pc=0x8b4418
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).run(0xc0004b4000, 0x6)
        pkg/sentry/kernel/task_run.go:92 +0x18b fp=0xc000171fd0 sp=0xc000171f60 pc=0x8b30eb
runtime.goexit()
        src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000171fd8 sp=0xc000171fd0 pc=0x467d61
created by gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).Start
        pkg/sentry/kernel/task_start.go:318 +0xfe
```

**Comment by ayushr2** [comment]
I believe this was fixed in https://github.com/google/gvisor/commit/ae59e529791e4763aaa25eee818605f17699fc67
