### ISSUE TITLE
go_marshal: maybe corrupting memory when unmarshalling

### ISSUE THREAD

**Issue by ridwanmsharif** [google/gvisor#3698]
To reproduce, run on a133d8f83b13fc189c957d5860ee970ba2d9023e as this doesn't have the temporary fix introduced by #3699 .

It looks as though go_marshal maybe corrupting memory when unmarshalling. This is reproduced when running a FUSE setup. Running FUSE with a passthrough FUSE daemon panics and kills the sentry (sometimes) when we try the `ls` command.

Steps to reproduce:

Use this or a similar Dockerfile to run a container sandbox:

```
FROM debian:stable
RUN apt update

RUN apt install -y build-essential git pkg-config fuse3 libfuse3-dev strace vim


WORKDIR /fuse-test

RUN mkdir mountpoint


RUN gcc -D_FILE_OFFSET_BITS=64  -Wall /usr/share/doc/libfuse3-dev/examples/hello.c `pkg-config fuse3 --cflags --libs` -o hello
RUN gcc -D_FILE_OFFSET_BITS=64  -Wall /usr/share/doc/libfuse3-dev/examples/passthrough.c `pkg-config fuse3 --cflags --libs` -o passthrough


CMD ["bash"]
```

Run the following commands:
```
$ docker run --runtime runsc  --privileged -it --rm b4c85473e5d0 bash
$ ./passthrough mountpoint # Launches a passthrough server.
$ ls mountpoint
```

This will cause different kinds of panic, one of which is:
```
panic: (runtime.boundsError) (0xf91da0,0xc000428740)
fatal error: panic holding locks

goroutine 52 [running]:
runtime.throw(0x105f0da, 0x13)
        GOROOT/src/runtime/panic.go:1116 +0x72 fp=0xc000635820 sp=0xc0006357f0 pc=0x434772
panic(0xf91da0, 0xc000428740)
        GOROOT/src/runtime/panic.go:917 +0x57e fp=0xc0006358d8 sp=0xc000635820 pc=0x43449e
runtime.goPanicIndex(0x33, 0x6)
        GOROOT/src/runtime/panic.go:88 +0xa3 fp=0xc000635920 sp=0xc0006358d8 pc=0x432083
sync.(*Pool).pinSlow(0x1a1d3e0, 0x0, 0x0)
        GOROOT/src/sync/pool.go:230 +0x27f fp=0xc0006359a0 sp=0xc000635920 pc=0x4746ff
sync.(*Pool).pin(0x1a1d3e0, 0x73, 0x12)
        GOROOT/src/sync/pool.go:206 +0x5e fp=0xc0006359c8 sp=0xc0006359a0 pc=0x47444e
sync.(*Pool).Put(0x1a1d3e0, 0xed6660, 0xc00036c5a0)
        GOROOT/src/sync/pool.go:102 +0x3d fp=0xc0006359f0 sp=0xc0006359c8 pc=0x47404d
```

Different runs will cause different panics. FOr now, FUSE is changing course and using the safe interface of go_marshal to avoid this issue until its fixed.

**Comment by mrahatm** [comment]
This doesn't seem like a memory corruption. Rather, this is a panic induced by missing `marshal.Marshallable` methods, which were intentionally left as stubs in `StubMarshallable`.
