### ISSUE TITLE
kernfs: passthrough FUSE server deadlocks when trying to stat itself

### ISSUE THREAD

**Issue by ridwanmsharif** [google/gvisor#3701]
**Description**
If you use a passthrough FUSE daemon or any daemon that stats itself then its possible that you find yourself in a deadlocked state.

**Steps to reproduce**

Use this or a similar Dockerfile to run a container sandbox:

```
FROM debian:stable
RUN apt update

RUN apt install -y build-essential git pkg-config fuse3 libfuse3-dev strace vim


WORKDIR /fuse-test

RUN mkdir mountpoint


RUN gcc -D_FILE_OFFSET_BITS=64  -Wall /usr/share/doc/libfuse3-dev/examples/hello.c `pkg-config fuse3 --cflags --libs` -o hello
RUN gcc -D_FILE_OFFSET_BITS=64  -Wall /usr/share/doc/libfuse3-dev/examples/passthrough.c `pkg-config fuse3 --cflags --libs` -o passthrough


CMD ["bash"]
```

Run the following commands:
```
$ docker run --runtime runsc  --privileged -it --rm b4c85473e5d0 bash
$ ./passthrough mountpoint # Launches a passthrough server.
$ stat mountpoint/fuse-test/mountpoint
```

This command will ***hang***. Use Ctl+C to stop.

**Problem**
When looking up an inode - kernfs acuires a filesystem-wide read lock (`fs.mu.RLock()`). This lookup request makes a blocking call to the fuse server so it can get the inode information. If the Server daemon then makes a Stat call to the same filesystem (as the passthrough server does above) then the Lookup task and the Server block each other when the server tries to acquire the filesystem-wide write lock (`fs.mu.Lock()`). Neither makes progress and we're stuck.

**Solution**
I don't know yet. This isn't a FUSE change exactly and requires buy-in from kernfs for a correct solution. I haven't investigated what Linux does. The easy fix probably involves not having the Lookup FUSE call wait while holding the RLock but I'm unfamiliar with the interactions here in thus subsystem.

**Helpful stack trace**
Maybe this helps the next person looking at the issue. We're blocked when trying to lock here: (`gvisor.dev/gvisor/pkg/sentry/fsimpl/kernfs.(*Filesystem).processDeferredDecRefs(...)`)

and the Lookup call blocks waiting on the server while holding the RLock.  
```
goroutine 60 [semacquire, 7 minutes]:
sync.runtime_Semacquire(0xc00042d918)
	GOROOT/src/runtime/sema.go:56 +0x42
gvisor.dev/gvisor/pkg/sync.(*RWMutex).Lock(0xc00042d910)
	pkg/sync/rwmutex_unsafe.go:144 +0x76
gvisor.dev/gvisor/pkg/sentry/fsimpl/kernfs.(*Filesystem).processDeferredDecRefs(0xc00042d8c0, 0x1222140, 0xc0004d4a80)
	pkg/sentry/fsimpl/kernfs/kernfs.go:122 +0x64
gvisor.dev/gvisor/pkg/sentry/fsimpl/kernfs.(*Filesystem).StatAt(0xc00042d8c0, 0x1222140, 0xc0004d4a80, 0xc0000ba000, 0x7ff, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	pkg/sentry/fsimpl/kernfs/filesystem.go:692 +0x258
gvisor.dev/gvisor/pkg/sentry/vfs.(*VirtualFilesystem).StatAt(0xc0001ae680, 0x1222140, 0xc0004d4a80, 0xc000432e40, 0xc0004e3a68, 0xc0004e3698, 0x0, 0x0, 0x0, 0x0, ...)
	pkg/sentry/vfs/vfs.go:569 +0xe7
gvisor.dev/gvisor/pkg/sentry/syscalls/linux/vfs2.fstatat(0xc0004d4a80, 0xc0ffffff9c, 0x2b8d80000bf0, 0x2b8d7bbffc80, 0x200000100, 0x0, 0x0)
	pkg/sentry/syscalls/linux/vfs2/stat.go:104 +0x29c
gvisor.dev/gvisor/pkg/sentry/syscalls/linux/vfs2.Lstat(0xc0004d4a80, 0x2b8d80000bf0, 0x2b8d7bbffc80, 0x2b8d7bbffc80, 0x0, 0x1, 0x2b8d7b571e80, 0x0, 0x16f74, 0x40000002, ...)
	pkg/sentry/syscalls/linux/vfs2/stat.go:41 +0x4f
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).executeSyscall(0xc0004d4a80, 0x6, 0x2b8d80000bf0, 0x2b8d7bbffc80, 0x2b8d7bbffc80, 0x0, 0x1, 0x2b8d7b571e80, 0x0, 0x10523e0, ...)
	pkg/sentry/kernel/task_syscall.go:170 +0x122
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallInvoke(0xc0004d4a80, 0x6, 0x2b8d80000bf0, 0x2b8d7bbffc80, 0x2b8d7bbffc80, 0x0, 0x1, 0x2b8d7b571e80, 0x1, 0x2b8d7b571e80)
	pkg/sentry/kernel/task_syscall.go:305 +0x66
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallEnter(0xc0004d4a80, 0x6, 0x2b8d80000bf0, 0x2b8d7bbffc80, 0x2b8d7bbffc80, 0x0, 0x1, 0x2b8d7b571e80, 0x11f4a01, 0x100000000000000)
	pkg/sentry/kernel/task_syscall.go:265 +0x96
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscall(0xc0004d4a80, 0x2, 0xc0004d4a80)
	pkg/sentry/kernel/task_syscall.go:240 +0x15c
gvisor.dev/gvisor/pkg/sentry/kernel.(*runApp).execute(0x0, 0xc0004d4a80, 0x11f4a40, 0x0)
	pkg/sentry/kernel/task_run.go:274 +0xc18
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).run(0xc0004d4a80, 0x5)
	pkg/sentry/kernel/task_run.go:92 +0x18b
created by gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).Start
	pkg/sentry/kernel/task_start.go:318 +0xfe

goroutine 71 [select, 7 minutes]:
gvisor.dev/gvisor/pkg/sentry/kernel/time.(*Timer).runGoroutine(0xc00047c000)
	pkg/sentry/kernel/time/time.go:515 +0xb6
created by gvisor.dev/gvisor/pkg/sentry/kernel/time.(*Timer).init
	pkg/sentry/kernel/time/time.go:494 +0x13f

goroutine 70 [select, 7 minutes]:
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).block(0xc0004d5500, 0xc0004e6900, 0x0, 0xc0000e70c0, 0x1092090)
	pkg/sentry/kernel/task_block.go:138 +0x16c
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).Block(...)
	pkg/sentry/kernel/task_block.go:110
gvisor.dev/gvisor/pkg/sentry/fsimpl/fuse.(*futureResponse).resolve(0xc0001fa480, 0xc0004d5500, 0xc0003b0300, 0xc0001fa480, 0x0)
	pkg/sentry/fsimpl/fuse/connection.go:450 +0x4f
gvisor.dev/gvisor/pkg/sentry/fsimpl/fuse.(*connection).call(0xc0004330e0, 0xc0004d5500, 0xc0003b0300, 0xc0004f7210, 0xc0004f7208, 0xc0004f7200)
	pkg/sentry/fsimpl/fuse/connection.go:334 +0x9b
gvisor.dev/gvisor/pkg/sentry/fsimpl/fuse.(*connection).Call(0xc0004330e0, 0xc0004d5500, 0xc0003b0300, 0xe9bae0, 0xc0004f71e8, 0xe9bae0)
	pkg/sentry/fsimpl/fuse/connection.go:297 +0x4a
gvisor.dev/gvisor/pkg/sentry/fsimpl/fuse.(*inode).newEntry(0xc000096480, 0xc0004d5500, 0xc0003b0300, 0xc0004fd815, 0xa, 0x1010000, 0xc0004d6880, 0xc0003b0300, 0x0)
	pkg/sentry/fsimpl/fuse/fusefs.go:485 +0x68
gvisor.dev/gvisor/pkg/sentry/fsimpl/fuse.(*inode).Lookup(0xc000096480, 0x1222140, 0xc0004d5500, 0xc0004fd815, 0xa, 0x41ed0001, 0xc000000000, 0x0)
	pkg/sentry/fsimpl/fuse/fusefs.go:381 +0x2d8
gvisor.dev/gvisor/pkg/sentry/fsimpl/kernfs.(*Filesystem).revalidateChildLocked(0xc00042d8c0, 0x1222140, 0xc0004d5500, 0xc0001ae680, 0xc000096528, 0xc0004fd815, 0xa, 0x0, 0xc000096528, 0x0, ...)
	pkg/sentry/fsimpl/kernfs/filesystem.go:133 +0x9f
gvisor.dev/gvisor/pkg/sentry/fsimpl/kernfs.(*Filesystem).stepExistingLocked(0xc00042d8c0, 0x1222140, 0xc0004d5500, 0xc000254000, 0xc000096528, 0x1, 0xc000096528, 0x0, 0x0)
	pkg/sentry/fsimpl/kernfs/filesystem.go:76 +0x1ec
gvisor.dev/gvisor/pkg/sentry/fsimpl/kernfs.(*Filesystem).walkExistingLocked(0xc00042d8c0, 0x1222140, 0xc0004d5500, 0xc000254000, 0x1, 0xc0001d9400, 0x0, 0x11f5de0, 0x1a58710)
	pkg/sentry/fsimpl/kernfs/filesystem.go:156 +0x6c
gvisor.dev/gvisor/pkg/sentry/fsimpl/kernfs.(*Filesystem).StatAt(0xc00042d8c0, 0x1222140, 0xc0004d5500, 0xc000254000, 0x7ff, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	pkg/sentry/fsimpl/kernfs/filesystem.go:689 +0x151
gvisor.dev/gvisor/pkg/sentry/vfs.(*VirtualFilesystem).StatAt(0xc0001ae680, 0x1222140, 0xc0004d5500, 0xc000432540, 0xc0001d9a68, 0xc0001d9698, 0x0, 0x0, 0x0, 0x0, ...)
	pkg/sentry/vfs/vfs.go:569 +0xe7
gvisor.dev/gvisor/pkg/sentry/syscalls/linux/vfs2.fstatat(0xc0004d5500, 0xc0ffffff9c, 0x7f24c3faaf0c, 0x7f24c3faabd0, 0x200000100, 0x0, 0x0)
	pkg/sentry/syscalls/linux/vfs2/stat.go:104 +0x29c
gvisor.dev/gvisor/pkg/sentry/syscalls/linux/vfs2.Lstat(0xc0004d5500, 0x7f24c3faaf0c, 0x7f24c3faabd0, 0x7f24c3faabd0, 0xfffffffffffff1d9, 0xaf, 0x560e350c27a0, 0x0, 0x16f6f, 0x40000002, ...)
	pkg/sentry/syscalls/linux/vfs2/stat.go:41 +0x4f
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).executeSyscall(0xc0004d5500, 0x6, 0x7f24c3faaf0c, 0x7f24c3faabd0, 0x7f24c3faabd0, 0xfffffffffffff1d9, 0xaf, 0x560e350c27a0, 0x0, 0x10523e0, ...)
	pkg/sentry/kernel/task_syscall.go:170 +0x122
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallInvoke(0xc0004d5500, 0x6, 0x7f24c3faaf0c, 0x7f24c3faabd0, 0x7f24c3faabd0, 0xfffffffffffff1d9, 0xaf, 0x560e350c27a0, 0xaf, 0x560e350c27a0)
	pkg/sentry/kernel/task_syscall.go:305 +0x66
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallEnter(0xc0004d5500, 0x6, 0x7f24c3faaf0c, 0x7f24c3faabd0, 0x7f24c3faabd0, 0xfffffffffffff1d9, 0xaf, 0x560e350c27a0, 0x1, 0x10000c00050d200)
	pkg/sentry/kernel/task_syscall.go:265 +0x96
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscall(0xc0004d5500, 0x2, 0xc0004d5500)
	pkg/sentry/kernel/task_syscall.go:240 +0x15c
gvisor.dev/gvisor/pkg/sentry/kernel.(*runApp).execute(0x0, 0xc0004d5500, 0x11f4a40, 0x0)
	pkg/sentry/kernel/task_run.go:274 +0xc18
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).run(0xc0004d5500, 0x6)
	pkg/sentry/kernel/task_run.go:92 +0x18b
created by gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).Start
	pkg/sentry/kernel/task_start.go:318 +0xfe
```

**Comment by ayushr2** [comment]
cc @manninglucas

**Comment by manninglucas** [comment]
@ayushr2 just checked, this doesn't repro at HEAD.
