### ISSUE TITLE
fuse: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by avagin** [google/gvisor#3963]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd1762d]

goroutine 74 [running]:
panic(0xf1f520, 0x1a90b40)
        GOROOT/src/runtime/panic.go:1064 +0x46d fp=0xc0002bb4b0 sp=0xc0002bb3f8 pc=0x43438d
runtime.panicmem(...)
        GOROOT/src/runtime/panic.go:212
runtime.sigpanic()
        GOROOT/src/runtime/signal_unix.go:695 +0x3da fp=0xc0002bb4e0 sp=0xc0002bb4b0 pc=0x44b93a
gvisor.dev/gvisor/pkg/sentry/fsimpl/fuse.(*DeviceFD).writeLocked(0xc0001a0200, 0x1261b00, 0xc000306a80, 0x1259540, 0xc0005cd000, 0x0, 0x0, 0x0, 0x0, 0x100, ...)
        pkg/sentry/fsimpl/fuse/dev.go:312 +0x91d fp=0xc0002bb760 sp=0xc0002bb4e0 pc=0xd1762d
gvisor.dev/gvisor/pkg/sentry/fsimpl/fuse.(*DeviceFD).Write(0xc0001a0200, 0x1261b00, 0xc000306a80, 0x1259540, 0xc0005cd000, 0x0, 0x1, 0x7f96015ffbe0, 0x10, 0x100, ...)
        pkg/sentry/fsimpl/fuse/dev.go:236 +0xfd fp=0xc0002bb800 sp=0xc0002bb760 pc=0xd16c7d
gvisor.dev/gvisor/pkg/sentry/vfs.(*FileDescription).Write(0xc0001a0200, 0x1261b00, 0xc000306a80, 0x1259540, 0xc0005cd000, 0x0, 0x1, 0x7f96015ffbe0, 0x10, 0x100, ...)
        pkg/sentry/vfs/file_description.go:607 +0xa1 fp=0xc0002bb880 sp=0xc0002bb800 pc=0x6be3e1
gvisor.dev/gvisor/pkg/sentry/syscalls/linux/vfs2.write(0xc000306a80, 0xc0001a0200, 0x1259540, 0xc0005cd000, 0x0, 0x1, 0x7f96015ffbe0, 0x10, 0x100, 0x0, ...)
        pkg/sentry/syscalls/linux/vfs2/read_write.go:364 +0x9b fp=0xc0002bba10 sp=0xc0002bb880 pc=0xc384fb
gvisor.dev/gvisor/pkg/sentry/syscalls/linux/vfs2.Writev(0xc000306a80, 0x3, 0x7f96015ffc20, 0x1, 0x0, 0x1, 0x7f96015fd386, 0x0, 0x0, 0x0, ...)
        pkg/sentry/syscalls/linux/vfs2/read_write.go:358 +0x1c5 fp=0xc0002bbb08 sp=0xc0002bba10 pc=0xc38285
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).executeSyscall(0xc000306a80, 0x14, 0x3, 0x7f96015ffc20, 0x1, 0x0, 0x1, 0x7f96015fd386, 0x0, 0x108b2e0, ...)
        pkg/sentry/kernel/task_syscall.go:103 +0x122 fp=0xc0002bbc68 sp=0xc0002bbb08 pc=0x8dce62
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallInvoke(0xc000306a80, 0x14, 0x3, 0x7f96015ffc20, 0x1, 0x0, 0x1, 0x7f96015fd386, 0x1, 0x7f96015fd386)
        pkg/sentry/kernel/task_syscall.go:238 +0x66 fp=0xc0002bbcf0 sp=0xc0002bbc68 pc=0x8de046
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallEnter(0xc000306a80, 0x14, 0x3, 0x7f96015ffc20, 0x1, 0x0, 0x1, 0x7f96015fd386, 0x1232801, 0x100000000000000)
        pkg/sentry/kernel/task_syscall.go:198 +0x96 fp=0xc0002bbd50 sp=0xc0002bbcf0 pc=0x8ddbd6
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscall(0xc000306a80, 0x2, 0xc000306a80)
        pkg/sentry/kernel/task_syscall.go:173 +0x15c fp=0xc0002bbe10 sp=0xc0002bbd50 pc=0x8dd56c
gvisor.dev/gvisor/pkg/sentry/kernel.(*runApp).execute(0x0, 0xc000306a80, 0x1232880, 0x0)
        pkg/sentry/kernel/task_run.go:275 +0xc18 fp=0xc0002bbf60 sp=0xc0002bbe10 pc=0x8d1f28
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).run(0xc000306a80, 0x6)
        pkg/sentry/kernel/task_run.go:93 +0x18b fp=0xc0002bbfd0 sp=0xc0002bbf60 pc=0x8d0bfb
runtime.goexit()
        src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0002bbfd8 sp=0xc0002bbfd0 pc=0x467da1
created by gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).Start
        pkg/sentry/kernel/task_start.go:318 +0xfe
```

**Comment by avagin** [comment]
Steps to reproduce:
$ cat Dockerfile
FROM debian:stable

RUN apt update

RUN apt install -y build-essential git pkg-config fuse3 libfuse3-dev strace vim


WORKDIR /fuse-test

RUN mkdir nomount


RUN gcc -D_FILE_OFFSET_BITS=64  -Wall /usr/share/doc/libfuse3-dev/examples/hello.c `pkg-config fuse3 --cflags --libs` -o hello
RUN gcc -D_FILE_OFFSET_BITS=64  -Wall /usr/share/doc/libfuse3-dev/examples/passthrough.c `pkg-config fuse3 --cflags --libs` -o passthrough


CMD ["bash"]
$ docker build -t fuse-test .
avagin@avagin:~/git/gvisor$ docker run --device /dev/fuse --runtime runsc  --privileged -it --rm fuse-test bash
root@fb4db15c7694:/fuse-test# ./passthrough nomount/
root@fb4db15c7694:/fuse-test# ls nomount/
avagin@avagin:~/git/gvisor$

**Comment by avagin** [comment]
```
root@3d1f6a85e64a:/fuse-test# ./hello -d nomount/ &
[1] 2
root@3d1f6a85e64a:/fuse-test# FUSE library version: 3.4.1
nullpath_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 2
INIT: 7.31
flags=0x00400000
max_readahead=0x00020000
   INIT: 7.27
   flags=0x00000020
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   time_gran=1
   unique: 2, success, outsize: 80

root@3d1f6a85e64a:/fuse-test# ls nomount
unique: 4, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 5
getattr[NULL] /
   unique: 4, success, outsize: 120
unique: 6, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 5
   unique: 6, success, outsize: 32
unique: 8, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 5
getattr[NULL] /
   unique: 8, success, outsize: 120
unique: 10, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 5
readdir[0] from 0
   unique: 10, success, outsize: 112
unique: 12, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 5
   unique: 12, success, outsize: 16
unique: 14, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 5
   unique: 14, success, outsize: 16
hello
```

**Comment by avagin** [comment]
We set noReply for FUSE_RELEASE requests, but a server sends replies on such requests.

**Comment by avagin** [comment]
```
                        fut, ok := fd.completions[hdr.Unique]
                        if !ok {
                               if fut.hdr.Unique == linux.FUSE_RELEASE {
```

* fut is always nil in this case.
* hdr.Unique isn't an opcode
