### ISSUE TITLE
tools/go_stateify:go_library doesn't support select() configurable attributes

### ISSUE THREAD

**Issue by xiaobo55x** [google/gvisor#398]
Hi,

We are adding the arm64 support for gVisor, and we ran into a bazel build issue for the pkg/sentry/arch package. 

pkg/sentry/arch/BUILD
```
  1 load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
  2 
  3 package(licenses = ["notice"])
  4 
  5 load("//tools/go_stateify:defs.bzl", "go_library")
  6 
  7 config_setting(
  8     name = "x86_64",
  9     constraint_values = ["@bazel_tools//platforms:x86_64"],
 10 )
 11 
 12 config_setting(
 13     name = "aarch64",
 14     constraint_values = ["@bazel_tools//platforms:aarch64"],
 15 )
 16 
 17 
 18 go_library(
 19     name = "arch",
 20     srcs = [
 21         "aligned.go",
 22         "arch.go",
 23         "auxv.go",
 24         "signal_act.go",
 25         "signal_info.go",
 26         "signal_stack.go",
 27         "stack.go",
 28     ] +
 29     select({
 30             ":x86_64":  ["arch_amd64.go", "arch_amd64.s", "arch_state_x86.go", "arch_x86.go", "signal_amd64.go", "syscalls_amd64.go",],
 31             ":aarch64": ["arch_arm64.go", "arch_state_aarch64.go", "arch_aarch64.go", "signal_arm64.go", "syscalls_arm64.go",],
 32         },
 33         no_match_error = "Unsupported architecture",
 34     ),
 35     importpath = "gvisor.googlesource.com/gvisor/pkg/sentry/arch",
 36     visibility = ["//:sandbox"],
 37     deps = [
 38         ":registers_go_proto",
 39         "//pkg/abi/linux",
 40         "//pkg/binary",
 41         "//pkg/cpuid",
 42         "//pkg/log",
 43         "//pkg/sentry/context",
 44         "//pkg/sentry/limits",
 45         "//pkg/sentry/usermem",
 46         "//pkg/syserror",
 47     ],
 48 )
 49 
 50 proto_library(
 51     name = "registers_proto",
 52     srcs = ["registers.proto"],
 53     visibility = ["//visibility:public"],
 54 )
 55 
 56 go_proto_library(
 57     name = "registers_go_proto",
 58     importpath = "gvisor.googlesource.com/gvisor/pkg/sentry/arch/registers_go_proto",
 59     proto = ":registers_proto",
 60     visibility = ["//visibility:public"],
 61 )
```

Bazel build error:
```
/home/test/go/src/gvisor.googlesource.com/gvisor-internal/pkg/sentry/arch# bazel build .
ERROR: /home/test/go/src/gvisor.googlesource.com/gvisor-internal/pkg/sentry/arch/BUILD:18:1: Traceback (most recent call last):
        File "/home/test/go/src/gvisor.googlesource.com/gvisor-internal/pkg/sentry/arch/BUILD", line 18
                go_library(name = "arch", srcs = (["aligned.g...")), <3 more arguments>)
        File "/home/test/go/src/gvisor.googlesource.com/gvisor-internal/tools/go_stateify/defs.bzl", line 85, in go_library
                "encode_unsafe.go" not in srcs
argument of type 'select' is not iterable. in operator only works on lists, tuples, dicts and strings.
ERROR: Skipping '.': no such target '//pkg/sentry/arch:arch': target 'arch' not declared in package 'pkg/sentry/arch' defined by /home/test/go/src/gvisor.googlesource.com/gvisor-internal/pkg/sentry/arch/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//pkg/sentry/arch:arch': target 'arch' not declared in package 'pkg/sentry/arch' defined by /home/test/go/src/gvisor.googlesource.com/gvisor-internal/pkg/sentry/arch/BUILD
INFO: Elapsed time: 0.207s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Comment by amscanne** [comment]
Why do you need select? Aren’t the build tags and file names enough?

Or does that lead to name conflicts? I think we just need to have go_stateify parse the build tags and/or file names and exclude things that don’t match GOOS and/or GOARCH. Does that sound good?

**Comment by prattmic** [comment]
Yes, I also think that build tag support in go_stateify should be sufficient. We'll need to figure out how to pass the target configuration to go_stateify (as it runs in host configuration). I'm sure this is possible in Starlark, though I don't actually know how.

**Comment by xiaobo55x** [comment]
@amscanne Yes, build tags and file names would lead to name conflicts. The root cause is that the go_stateify doesn't parse the build tags and file names.

**Comment by xiaobo55x** [comment]
@prattmic Another tool we need to enable the build tag support is the tools/go_generics:go_template.

**Comment by amscanne** [comment]
Maybe we can fix this without having to do skylark.

If the tools can generate multiple output files (unclear if possible for
inclusion in other rules), then we can simply _preserve_ all build tags
and/or suffixes.

**Comment by lubinsz** [comment]
Hi @amscanne @prattmic 

I have a solution for this issue, please check it:
https://github.com/google/gvisor/pull/1025

Thanks.

**Comment by lubinszARM** [comment]
Hi @xiaobo55x 
This issue has gone.
Can we close it?
Thanks.

**Comment by xiaobo55x** [comment]
@lubinsz Yes!
