### ISSUE TITLE
panic: remote-revalidating cache policy requires gofer to donate host FD, but file XXX did not have host FD

### ISSUE THREAD

**Issue by aaronlu** [google/gvisor#4020]
I used a bash image and runsc to start a sandbox and in config.json, I bind mounted a local directory where linux kernel tree is located. In the sandboxed container, I issued the following cmd:
bash-5.0# time for i in `find mnt/linux/4.19/src -type f`; do cat $i > /dev/null; done
And the sandbox would panic after some time:
panic: remote-revalidating cache policy requires gofer to donate host FD, but file "sysfs-class-fpga-region" did not have host FD

and the callstack is:
goroutine 68962 [running]:
panic(0xeec940, 0xc0002083d0)
        GOROOT/src/runtime/panic.go:1064 +0x46d fp=0xc00146d6a0 sp=0xc00146d5e8 pc=0x43438d
gvisor.dev/gvisor/pkg/sentry/fs/gofer.NewFile(0x1292640, 0xc000db4a80, 0xc000a92420, 0xc00117962d, 0x17, 0x100010000000000, 0x1000001, 0xc0008bdb20, 0xc001328d20, 0xc0011d59e0)
        pkg/sentry/fs/gofer/file.go:93 +0x3b6 fp=0xc00146d738 sp=0xc00146d6a0 pc=0xb6cb86
gvisor.dev/gvisor/pkg/sentry/fs/gofer.(*inodeOperations).getFileDefault(0xc0008bdb20, 0x1292640, 0xc000db4a80, 0xc000a92420, 0x10000000000, 0x1000000, 0xc0008bdb20, 0x1292640, 0xc000db4a80)
        pkg/sentry/fs/gofer/inode.go:546 +0x120 fp=0xc00146d7a0 sp=0xc00146d738 pc=0xb73020
gvisor.dev/gvisor/pkg/sentry/fs/gofer.(*inodeOperations).GetFile(0xc0008bdb20, 0x1292640, 0xc000db4a80, 0xc000a92420, 0x10000000000, 0x1000000, 0x1000001, 0x0, 0x0)
        pkg/sentry/fs/gofer/inode.go:482 +0xe5 fp=0xc00146d7f8 sp=0xc00146d7a0 pc=0xb725b5
gvisor.dev/gvisor/pkg/sentry/fs.(*Inode).GetFile(0xc000abdc00, 0x1292640, 0xc000db4a80, 0xc000a92420, 0x10000000000, 0x1000000, 0x0, 0x17, 0xc000db4a80)
        pkg/sentry/fs/inode.go:251 +0xf3 fp=0xc00146d850 sp=0xc00146d7f8 pc=0x6acd23
gvisor.dev/gvisor/pkg/sentry/syscalls/linux.openAt.func1(0xc00039a840, 0xc000a92420, 0x28, 0x0, 0x0)
        pkg/sentry/syscalls/linux/sys_file.go:186 +0x292 fp=0xc00146d970 sp=0xc00146d850 pc=0x97f972
gvisor.dev/gvisor/pkg/sentry/syscalls/linux.fileOpOn(0xc000db4a80, 0x7fcfffffff9c, 0xc001179600, 0x44, 0x1, 0xc00146da80, 0x0, 0x0)
        pkg/sentry/syscalls/linux/sys_file.go:112 +0x1e1 fp=0xc00146da40 sp=0xc00146d970 pc=0x946101
gvisor.dev/gvisor/pkg/sentry/syscalls/linux.openAt(0xc000db4a80, 0xc0ffffff9c, 0x7fcfd948cf2a, 0x0, 0x0, 0x200000003, 0xc0006e5b00)
        pkg/sentry/syscalls/linux/sys_file.go:143 +0x112 fp=0xc00146dab8 sp=0xc00146da40 pc=0x946572
gvisor.dev/gvisor/pkg/sentry/syscalls/linux.Open(0xc000db4a80, 0x7fcfd948cf2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x21e6, 0x40000002, ...)
        pkg/sentry/syscalls/linux/sys_file.go:473 +0xb7 fp=0xc00146db08 sp=0xc00146dab8 pc=0x946b17
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).executeSyscall(0xc000db4a80, 0x2, 0x7fcfd948cf2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10afa60, ...)
        pkg/sentry/kernel/task_syscall.go:104 +0x122 fp=0xc00146dc68 sp=0xc00146db08 pc=0x8ef512
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallInvoke(0xc000db4a80, 0x2, 0x7fcfd948cf2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        pkg/sentry/kernel/task_syscall.go:239 +0x66 fp=0xc00146dcf0 sp=0xc00146dc68 pc=0x8f06f6
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallEnter(0xc000db4a80, 0x2, 0x7fcfd948cf2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1262801, 0x100000000000000)
        pkg/sentry/kernel/task_syscall.go:199 +0x96 fp=0xc00146dd50 sp=0xc00146dcf0 pc=0x8f0286
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscall(0xc000db4a80, 0x2, 0xc000db4a80)
        pkg/sentry/kernel/task_syscall.go:174 +0x15c fp=0xc00146de10 sp=0xc00146dd50 pc=0x8efc1c
gvisor.dev/gvisor/pkg/sentry/kernel.(*runApp).execute(0x0, 0xc000db4a80, 0x1262820, 0x0)
        pkg/sentry/kernel/task_run.go:275 +0xc18 fp=0xc00146df60 sp=0xc00146de10 pc=0x8e45d8
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).run(0xc000db4a80, 0x15a)
        pkg/sentry/kernel/task_run.go:93 +0x18b fp=0xc00146dfd0 sp=0xc00146df60 pc=0x8e32eb
runtime.goexit()
        src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00146dfd8 sp=0xc00146dfd0 pc=0x467da1
created by gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).Start
        pkg/sentry/kernel/task_start.go:318 +0xfe

This is tested with:
commit ca308747205020c957d7fea3929f6c26004a6dd3 (HEAD -> master, origin/master, origin/HEAD)
Merge: 916751039 ac324f646
Author: gVisor bot <gvisor-bot@google.com>
Date:   Sun Sep 20 18:17:20 2020 -0700

    Merge pull request #3651 from ianlewis:ip-forwarding
    
    PiperOrigin-RevId: 332760843

And platform ptrace. Any idea?

**Comment by aaronlu** [comment]
BTW, I just tried platform kvm and it failed with the same error.

**Comment by aaronlu** [comment]
It appears this has something to do with user's limit of open files. If I specify: ulimit -n 65536 before starting the sandbox(the default is 1024), everything will work well. So I'm closing this issue.
