### ISSUE TITLE
arm64: ptrace platform can not work

### ISSUE THREAD

**Issue by lemin9538** [google/gvisor#4041]
Hi

I use ptrace platform (gvisor commit id is  742e58b873dbb8d3c14b2e40f212df90ec837671 ) to start the container on my arm64 server, but failed. The below steps can reproduce this issue:

1 - prepare a rootfs like busybox
2 - run  "runsc --platform=ptrace --debug=true --debug-log=./1.txt run 123"

```
DataVersion: 0}, QIDs: [QID{Type: 0, Version: 0, Path: 2496804}]}
D0922 09:06:19.664052   99917 transport_flipcall.go:127] send [channel @0x40001f0300] Tgetxattr{FID: 7, Name: trusted.overlay.whiteout.hello, Size: 1}
D0922 09:06:19.664067       1 transport_flipcall.go:234] recv [channel @0x40001f0a80] Tgetxattr{FID: 7, Name: trusted.overlay.whiteout.hello, Size: 1}
D0922 09:06:19.664081       1 transport_flipcall.go:127] send [channel @0x40001f0a80] Rlerror{Error: 95}
D0922 09:06:19.664095   99917 transport_flipcall.go:234] recv [channel @0x40001f0300] Rlerror{Error: 95}
D0922 09:06:19.664111   99917 transport_flipcall.go:127] send [channel @0x40001f0300] Twalk{FID: 8, NewFID: 9, Names: []}
D0922 09:06:19.664126       1 transport_flipcall.go:234] recv [channel @0x40001f0a80] Twalk{FID: 8, NewFID: 9, Names: []}
D0922 09:06:19.664147       1 transport_flipcall.go:127] send [channel @0x40001f0a80] Rwalk{QIDs: []}
D0922 09:06:19.664161   99917 transport_flipcall.go:234] recv [channel @0x40001f0300] Rwalk{QIDs: []}
D0922 09:06:19.664172   99917 transport_flipcall.go:127] send [channel @0x40001f0300] Tlopen{FID: 9, Flags: ReadOnly}
D0922 09:06:19.664187       1 transport_flipcall.go:234] recv [channel @0x40001f0a80] Tlopen{FID: 9, Flags: ReadOnly}
D0922 09:06:19.664197       1 fsgofer.go:380] Open reusing control file, flags: ReadOnly, "/bin/hello"
D0922 09:06:19.664212       1 transport_flipcall.go:127] send [channel @0x40001f0a80] Rlopen{QID: QID{Type: 0, Version: 0, Path: 2496804}, IoUnit: 0, File: FD: 34}
D0922 09:06:19.664242   99917 transport_flipcall.go:234] recv [channel @0x40001f0300] Rlopen{QID: QID{Type: 0, Version: 0, Path: 2496804}, IoUnit: 0, File: FD: 25}
D0922 09:06:19.664392   99917 syscalls.go:256] Allocating stack with size of 8388608 bytes 
W0922 09:06:19.664555   99917 loader.go:792] Seccomp spec is being ignored
I0922 09:06:19.664835   99917 loader.go:613] Process should have started...
I0922 09:06:19.664865   99917 watchdog.go:211] Starting watchdog, period: 45s, timeout: 3m0s, action: 0
D0922 09:06:19.664953   99917 urpc.go:534] urpc: successfully marshalled 37 bytes.
D0922 17:06:19.664967   99910 urpc.go:577] urpc: unmarshal success.
D0922 17:06:19.664986   99910 container.go:784] Save container "123" 
D0922 17:06:19.665203   99910 state_file.go:54] List containers "/run/user/0/runsc"
D0922 17:06:19.665272   99910 container.go:162] Load container "/run/user/0/runsc" "123" 
D0922 09:06:19.665335   99917 task_block.go:223] [   1] Interrupt queued
panic: ptrace sysemu failed: input/output error 

goroutine 311 [running]:
panic(0x9d3040, 0x4000714070)
        GOROOT/src/runtime/panic.go:1064 +0x420 fp=0x400060ec10 sp=0x400060eb50 pc=0x41dd0
gvisor.dev/gvisor/pkg/sentry/platform/ptrace.(*subprocess).switchToApp(0x400022e180, 0x40001f0540D0922 17:06:19.666211   99910 container.go:595] Signal container "123": signal 0
, 0xd9cb20, 0x4000012b00, D0922 17:06:19.666226   99910 sandbox.go:829] Signal sandbox "123" 
0x9d2700)
        pkg/sentry/platform/ptrace/subprocess.goD0922 17:06:19.666235   99910 sandbox.go:334] Connecting to sandbox "123" 
:546 +0x734 fp=0x400060ed20 sp=0x400060ec10 pc=0x7e05d4
gvisor.dev/gvisor/pkg/sentry/platform/ptrace.(*context).Switch(0x40001f0540, 0xd87660, 0x400030e000, 0xd81e60, 0x4000430000, 0xd9cb20, 0x4000012b00, 0xffffffff, 0x0, 0x0, ...)
        D0922 17:06:19.666282   99910 urpc.go:534] urpc: successfully marshalled 83 bytes.
pkg/sentry/platform/ptrace/ptrace.go:102 +0x6c fp=0x400060edd0 sp=0x400060ed20 pc=0x7dd28c
gvisor.dev/gvisor/pkg/sentry/kernel.(*runApp).execute(0x0, 0x400030e000, 0xd57740, 0x0)
        pkg/sentry/kernel/task_run.go:264 +0x2b8 fp=0x400060ef50 sp=0x400060edd0 pc=0x47ff78
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).run(0x400030e000, 0x1)
        pkg/sentry/kernel/task_run.go:93 +0x17c fp=0x400060efc0 sp=0x400060ef50 pc=0x47f63c
runtime.goexit()
        src/runtime/asm_arm64.s:1148 +0x4 fp=0x400060efc0 sp=0x400060efc0 pc=0x74b54
```
The full log are attached. 
[1.txt](https://github.com/google/gvisor/files/5260804/1.txt)

**Comment by lubinszARM** [comment]
Hi @lemin9538 
Can you provide the kernel version?
Linux's arm64 ptrace sysemu feature was introduced in 5.3+

**Comment by lemin9538** [comment]
Hi @lubinszARM 

I am using the kernel 4.19.91.

**Comment by lubinszARM** [comment]
Hi @lubinszARM 
Please try kernel 5.3+.
If there is any problem, please let me know.
Thanks.

**Comment by lemin9538** [comment]
Hi @lubinszARM 

Ok, Got it.

Two more questions:
1 - So there is no plan to make ptrace platform support the kernel version which below 5.3 (due to sysemu issue) ?
2 - Does the KVM platform also verified on kernel 5.3+, I found KVM platform can not work on kernel 4.19 too.

Thanks
Le Min

**Comment by lubinszARM** [comment]
@lemin9538 
1,
No plan for it. You can try to back port the sysemu related patches.
2,
In my opinion,  kvm platform is OK with low kernel version.  I guess only a few minor changes are needed, such as PSCI and some other ioctl commands.

**Comment by lemin9538** [comment]
@lubinszARM 

Ok, understand. Close this issue.

Thanks.
