### ISSUE TITLE
panic: gofer.dentry.decRefNoCaching() called without holding a reference

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#5263]
Repro: Run the following using runsc with VFS2 enabled: `fsstress -d /test -n 10000 -p 100 -X -seed 1610087342`

```
panic: gofer.dentry.decRefNoCaching() called without holding a reference

goroutine 488 [running]:
panic(0x103ffe0, 0x1377ad0)
        third_party/go/gc/src/runtime/panic.go:1066 +0x557 fp=0xc000ecd810 sp=0xc000ecd710 pc=0x439057
google3/third_party/gvisor/pkg/sentry/fsimpl/gofer/gofer.(*dentry).decRefNoCaching(0xc00198e000, 0xc00198e1d0)
        third_party/gvisor/pkg/sentry/fsimpl/gofer/gofer.go:1280 +0x65 fp=0xc000ecd830 sp=0xc000ecd810 pc=0xc83305
google3/third_party/gvisor/pkg/sentry/fsimpl/gofer/gofer.(*dentry).DecRef(0xc00198e000, 0x13c07e0, 0xc000496a80)
        third_party/gvisor/pkg/sentry/fsimpl/gofer/gofer.go:1264 +0x2f fp=0xc000ecd858 sp=0xc000ecd830 pc=0xc8320f
google3/third_party/gvisor/pkg/sentry/fsimpl/gofer/gofer.(*filesystem).Sync(0xc000494000, 0x13c07e0, 0xc000496a80, 0x0, 0x0)
        third_party/gvisor/pkg/sentry/fsimpl/gofer/filesystem.go:59 +0x487 fp=0xc000ecda10 sp=0xc000ecd858 pc=0xc740c7
google3/third_party/gvisor/pkg/sentry/vfs/vfs.(*VirtualFilesystem).SyncAllFilesystems(0xc00018fd10, 0x13c07e0, 0xc000496a80, 0x300000002, 0xc000d91c80)
        third_party/gvisor/pkg/sentry/vfs/vfs.go:788 +0x12d fp=0xc000ecdac0 sp=0xc000ecda10 pc=0x8471ad
google3/third_party/gvisor/pkg/sentry/syscalls/linux/vfs2/vfs2.Sync(0xc000496a80, 0x8c, 0x74d0fa9, 0x1c, 0x1, 0x18, 0xfefefefefefefeff, 0x3d, 0x356cd8, 0xc000ecdbe4, ...)
        third_party/gvisor/pkg/sentry/syscalls/linux/vfs2/sync.go:26 +0x4c fp=0xc000ecdaf8 sp=0xc000ecdac0 pc=0xe0252c
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).executeSyscall(0xc000496a80, 0xa2, 0x8c, 0x74d0fa9, 0x1c, 0x1, 0x18, 0xfefefefefefefeff, 0x1, 0x1225320, ...)
        third_party/gvisor/pkg/sentry/kernel/task_syscall.go:104 +0x13c fp=0xc000ecdc58 sp=0xc000ecdaf8 pc=0xa39bdc
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).doSyscallInvoke(0xc000496a80, 0xa2, 0x8c, 0x74d0fa9, 0x1c, 0x1, 0x18, 0xfefefefefefefeff, 0x18, 0xfefefefefefefeff)
        third_party/gvisor/pkg/sentry/kernel/task_syscall.go:239 +0x66 fp=0xc000ecdce0 sp=0xc000ecdc58 pc=0xa3ada6
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).doSyscallEnter(0xc000496a80, 0xa2, 0x8c, 0x74d0fa9, 0x1c, 0x1, 0x18, 0xfefefefefefefeff, 0xe41c4e, 0xc000b5cee0)
        third_party/gvisor/pkg/sentry/kernel/task_syscall.go:199 +0x98 fp=0xc000ecdd40 sp=0xc000ecdce0 pc=0xa3a958
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).doSyscall(0xc000496a80, 0x2, 0xc000496a80)
        third_party/gvisor/pkg/sentry/kernel/task_syscall.go:174 +0x15c fp=0xc000ecde10 sp=0xc000ecdd40 pc=0xa3a2fc
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*runApp).execute(0x0, 0xc000496a80, 0x13911c0, 0x0)
        third_party/gvisor/pkg/sentry/kernel/task_run.go:282 +0xc45 fp=0xc000ecdf60 sp=0xc000ecde10 pc=0xa2e705
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).run(0xc000496a80, 0x66)
        third_party/gvisor/pkg/sentry/kernel/task_run.go:97 +0x1af fp=0xc000ecdfd0 sp=0xc000ecdf60 pc=0xa2d3cf
runtime.goexit()
        third_party/go/gc/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000ecdfd8 sp=0xc000ecdfd0 pc=0x475181
created by google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).Start
        third_party/gvisor/pkg/sentry/kernel/task_start.go:323 +0xfe
```

**Comment by nixprime** [comment]
Please add what fsstress is and how to build it to your repro instructions.

**Comment by nixprime** [comment]
Never mind, figured it out (although note that `fsstress` doesn't take long flags, so `-seed` must be `-s`).

**Comment by fvoznika** [comment]
It's still happening: 
```shell
$ docker run --rm --runtime=runsc-vfs2 gvisor.dev/images/basic/fsstress -d /test -n 1000 -p 100 -X
seed = 1611865242
```

```
panic: gofer.dentry.decRefNoCaching() called without holding a reference

goroutine 295 [running]:
panic(0x103cfe0, 0x1378590)
	third_party/go/gc/src/runtime/panic.go:1066 +0x557 fp=0xc000c47808 sp=0xc000c47708 pc=0x439057
google3/third_party/gvisor/pkg/sentry/fsimpl/gofer/gofer.(*dentry).decRefNoCaching(0xc0043b6800, 0xc0043b69d0)
	third_party/gvisor/pkg/sentry/fsimpl/gofer/gofer.go:1280 +0x65 fp=0xc000c47828 sp=0xc000c47808 pc=0xc7ddc5
google3/third_party/gvisor/pkg/sentry/fsimpl/gofer/gofer.(*dentry).DecRef(0xc0043b6800, 0x13c13e0, 0xc000bd8a80)
	third_party/gvisor/pkg/sentry/fsimpl/gofer/gofer.go:1264 +0x2f fp=0xc000c47850 sp=0xc000c47828 pc=0xc7dccf
google3/third_party/gvisor/pkg/sentry/fsimpl/gofer/gofer.(*filesystem).Sync(0xc000512000, 0x13c13e0, 0xc000bd8a80, 0x0, 0x0)
	third_party/gvisor/pkg/sentry/fsimpl/gofer/filesystem.go:69 +0x4c7 fp=0xc000c47a10 sp=0xc000c47850 pc=0xc6ed07
google3/third_party/gvisor/pkg/sentry/vfs/vfs.(*VirtualFilesystem).SyncAllFilesystems(0xc000382190, 0x13c13e0, 0xc000bd8a80, 0x300000002, 0xc000ba8900)
	third_party/gvisor/pkg/sentry/vfs/vfs.go:788 +0x12d fp=0xc000c47ac0 sp=0xc000c47a10 pc=0x84934d
google3/third_party/gvisor/pkg/sentry/syscalls/linux/vfs2/vfs2.Sync(0xc000bd8a80, 0x112, 0x55ab3e1a, 0xe, 0x0, 0xa, 0x561e06b3fe90, 0x3d, 0x8b265, 0xc000c47be4, ...)
	third_party/gvisor/pkg/sentry/syscalls/linux/vfs2/sync.go:26 +0x4c fp=0xc000c47af8 sp=0xc000c47ac0 pc=0xdfd4ac
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).executeSyscall(0xc000bd8a80, 0xa2, 0x112, 0x55ab3e1a, 0xe, 0x0, 0xa, 0x561e06b3fe90, 0x1, 0x12254e0, ...)
	third_party/gvisor/pkg/sentry/kernel/task_syscall.go:104 +0x13c fp=0xc000c47c58 sp=0xc000c47af8 pc=0xa36e5c
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).doSyscallInvoke(0xc000bd8a80, 0xa2, 0x112, 0x55ab3e1a, 0xe, 0x0, 0xa, 0x561e06b3fe90, 0xa, 0x561e06b3fe90)
	third_party/gvisor/pkg/sentry/kernel/task_syscall.go:239 +0x66 fp=0xc000c47ce0 sp=0xc000c47c58 pc=0xa38026
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).doSyscallEnter(0xc000bd8a80, 0xa2, 0x112, 0x55ab3e1a, 0xe, 0x0, 0xa, 0x561e06b3fe90, 0xe3ccae, 0xc00063ae20)
	third_party/gvisor/pkg/sentry/kernel/task_syscall.go:199 +0x98 fp=0xc000c47d40 sp=0xc000c47ce0 pc=0xa37bd8
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).doSyscall(0xc000bd8a80, 0x2, 0xc000bd8a80)
	third_party/gvisor/pkg/sentry/kernel/task_syscall.go:174 +0x15c fp=0xc000c47e10 sp=0xc000c47d40 pc=0xa3757c
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*runApp).execute(0x0, 0xc000bd8a80, 0x1391e80, 0x0)
	third_party/gvisor/pkg/sentry/kernel/task_run.go:282 +0xc45 fp=0xc000c47f60 sp=0xc000c47e10 pc=0xa2b985
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).run(0xc000bd8a80, 0x41)
	third_party/gvisor/pkg/sentry/kernel/task_run.go:97 +0x1af fp=0xc000c47fd0 sp=0xc000c47f60 pc=0xa2a64f
runtime.goexit()
	third_party/go/gc/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000c47fd8 sp=0xc000c47fd0 pc=0x475181
created by google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).Start
	third_party/gvisor/pkg/sentry/kernel/task_start.go:323 +0xfe
```
