### ISSUE TITLE
kvm: floating-point exception code=0x6 addr=0x425ea9 pc=0x425ea9

### ISSUE THREAD

**Issue by avagin** [google/gvisor#5754]
https://syzkaller.appspot.com/text?tag=CrashLog&x=12992127200000

```
fatal error: unexpected signal during runtime execution
[signal SIGFPE: floating-point exception code=0x6 addr=0x425ea9 pc=0x425ea9]

goroutine 459036 [running, locked to thread]:
runtime.throw(0x120371e, 0x2a)
        GOROOT/src/runtime/panic.go:1116 +0x72 fp=0xc00403f808 sp=0xc00403f7d8 pc=0x437672
runtime.sigpanic()
        GOROOT/src/runtime/signal_unix.go:726 +0x4ac fp=0xc00403f838 sp=0xc00403f808 pc=0x44e12c
runtime.deductSweepCredit(0x2000, 0x0)
        GOROOT/src/runtime/mgcsweep.go:862 +0xe9 fp=0xc00403f860 sp=0xc00403f838 pc=0x425ea9
runtime.(*mcentral).cacheSpan(0x1b27738, 0x9)
        GOROOT/src/runtime/mcentral.go:101 +0x65 fp=0xc00403f8d8 sp=0xc00403f860 pc=0x418625
runtime.(*mcache).refill(0x7f55ec2ad560, 0x57)
        GOROOT/src/runtime/mcache.go:142 +0xa5 fp=0xc00403f8f8 sp=0xc00403f8d8 pc=0x418345
runtime.(*mcache).nextFree(0x7f55ec2ad560, 0x57, 0x0, 0x0, 0x0)
        GOROOT/src/runtime/malloc.go:880 +0x8d fp=0xc00403f930 sp=0xc00403f8f8 pc=0x40d46d
runtime.mallocgc(0x1000, 0x1037e60, 0xc009372001, 0x0)
        GOROOT/src/runtime/malloc.go:1061 +0x834 fp=0xc00403f9d0 sp=0xc00403f930 pc=0x40de54
runtime.newobject(0x1037e60, 0xc00403fa88)
        GOROOT/src/runtime/malloc.go:1195 +0x38 fp=0xc00403fa00 sp=0xc00403f9d0 pc=0x40e2f8
gvisor.dev/gvisor/pkg/ring0/pagetables.newAlignedPTEs(...)
        pkg/ring0/pagetables/allocator_unsafe.go:25
gvisor.dev/gvisor/pkg/ring0/pagetables.(*RuntimeAllocator).NewPTEs(0xc0092655c0, 0x10)
        pkg/ring0/pagetables/allocator.go:103 +0x39 fp=0xc00403fa38 sp=0xc00403fa00 pc=0xdeee19
gvisor.dev/gvisor/pkg/sentry/platform/kvm.(*allocator).NewPTEs(0xc0092655c0, 0x0)
        pkg/sentry/platform/kvm/bluepill_allocator.go:49 +0x1e fp=0xc00403fa60 sp=0xc00403fa38 pc=0xdf6abe
gvisor.dev/gvisor/pkg/ring0/pagetables.(*mapWalker).iterateRangeCanonical(0xc00403fb60, 0x401000, 0x4a8000, 0x3f54fec08000)
        bazel-out/k8-fastbuild-ST-4c64f0b3d5c7/bin/pkg/ring0/pagetables/walker_map_amd64.go:21 +0x982 fp=0xc00403fb18 sp=0xc00403fa60 pc=0xdf1922
gvisor.dev/gvisor/pkg/ring0/pagetables.(*mapWalker).iterateRange(0xc00403fb60, 0x401000, 0x4a8000)
        bazel-out/k8-fastbuild-ST-4c64f0b3d5c7/bin/pkg/ring0/pagetables/walker_map_amd64.go:227 +0x5d fp=0xc00403fb48 sp=0xc00403fb18 pc=0xdf1a3d
gvisor.dev/gvisor/pkg/ring0/pagetables.(*PageTables).Map(0xc009265600, 0x401000, 0xa7000, 0x100010001, 0x3f54fec08000, 0x4)
        pkg/ring0/pagetables/pagetables.go:169 +0xd3 fp=0xc00403fb90 sp=0xc00403fb48 pc=0xdef4f3
gvisor.dev/gvisor/pkg/sentry/platform/kvm.(*addressSpace).mapLocked(0xc001b4e580, 0x401000, 0x3f53fec08000, 0xa7000, 0x10001, 0x0)
        pkg/sentry/platform/kvm/address_space.go:141 +0xdb fp=0xc00403fbf0 sp=0xc00403fb90 pc=0xdf5d5b
gvisor.dev/gvisor/pkg/sentry/platform/kvm.(*addressSpace).MapFile(0xc001b4e580, 0x401000, 0x134e4e0, 0xc00009aba0, 0x1000, 0xa8000, 0x10001, 0x0, 0x0)
        pkg/sentry/platform/kvm/address_space.go:199 +0x2ba fp=0xc00403fcd0 sp=0xc00403fbf0 pc=0xdf60ba
gvisor.dev/gvisor/pkg/sentry/mm.(*MemoryManager).mapASLocked(0xc009372000, 0xc009372800, 0x1, 0x467000, 0x468000, 0x467000, 0x468000, 0x10001)
        pkg/sentry/mm/address_space.go:209 +0x1b1 fp=0xc00403fd48 sp=0xc00403fcd0 pc=0x84d991
gvisor.dev/gvisor/pkg/sentry/mm.(*MemoryManager).HandleUserFault(0xc009372000, 0x135be60, 0xc00957b500, 0x4679a8, 0x1010001, 0x7fa0e5284a00, 0xc0064959e0, 0xc0ffffffff)
        pkg/sentry/mm/syscalls.go:69 +0x291 fp=0xc00403fe10 sp=0xc00403fd48 pc=0x872531
gvisor.dev/gvisor/pkg/sentry/kernel.(*runApp).execute(0x0, 0xc00957b500, 0x132bde0, 0x0)
        pkg/sentry/kernel/task_run.go:311 +0x6bc fp=0xc00403ff60 sp=0xc00403fe10 pc=0x9cd99c
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).run(0xc00957b500, 0x81f1)
        pkg/sentry/kernel/task_run.go:97 +0x1af fp=0xc00403ffd0 sp=0xc00403ff60 pc=0x9ccbef
runtime.goexit()
        src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00403ffd8 sp=0xc00403ffd0 pc=0x4709a1
created by gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).Start
        pkg/sentry/kernel/task_start.go:323 +0xfe
```

**Comment by avagin** [comment]
https://github.com/golang/go/blob/597b5d192e39d7bba38dd461b96effe6e524984b/src/cmd/compile/abi-internal.md#flags

```
The MXCSR status bits are callee-save.

*Rationale*: Having a fixed MXCSR control configuration allows Go
functions to use SSE operations without modifying or saving the MXCSR.
Functions are allowed to modify it between calls (as long as they
restore it), but as of this writing Go code never does.
The above fixed configuration matches the process initialization
control bits specified by the ELF AMD64 ABI.

The x87 floating-point control word is not used by Go on amd64.
```

**Comment by avagin** [comment]
https://cs.opensource.google/gvisor/gvisor/+/master:pkg/ring0/kernel_amd64.go;l=251?q=switchtouser&ss=gvisor%2Fgvisor

ring0.CPU.SwitchToUser doesn't restore the Sentry mxcsr.

And if we don't restore a sentry floating point state, we can be affected by another problem:
```
If software inter-mixes AVX and SSE instructions without using VZEROUPPER properly, it can experience
an AVX/SSE transition penalty. The situations of executing SSE, AVX, or managing the YMM state using
XSAVE/XRSTOR/VZEROUPPER/VZEROALL is illustrated in Figure 11-1. The penalty associated with transitions into or out of the processor state “Modified and Unsaved” is implementation specific, depending
on the microarchitecture. 
```

**Comment by avagin** [comment]
Here is a small reproducer:

```
#include <stdio.h>
#include <unistd.h>

int main()
{
 unsigned int mxcsr;

 __asm__ ("STMXCSR %0" : "=m"(mxcsr));
 printf("%x\n", mxcsr);
 mxcsr = 0;
 __asm__ ("LDMXCSR %0"
     :
     : "m"(mxcsr)
     );
 __asm__ ("STMXCSR %0" : "=m"(mxcsr));
 printf("%x\n", mxcsr);
 return 0;
}
```

```
$ gcc mxcsr.c
$ unlink /tmp/runsc.log; runsc --rootless --network none --platform kvm --debug --debug-log /tmp/runsc.log do sh -c 'while :; do ./a.out && echo ok; done'
1f80
0
$ cat /tmp/runsc.log | grep -A 5 -B 5 fatal 
D0402 16:01:10.190206       1 transport_flipcall.go:127] send [channel @0xc0004d2300] Treadlink{FID: 44}
D0402 23:01:10.190276       1 transport_flipcall.go:234] recv [channel @0xc000332240] Treadlink{FID: 44}
D0402 23:01:10.190318       1 transport_flipcall.go:127] send [channel @0xc000332240] Rreadlink{Target: libc-2.31.so}
D0402 16:01:10.190410       1 transport_flipcall.go:234] recv [channel @0xc0004d2300] Rreadlink{Target: libc-2.31.so}
D0402 16:01:10.192193       1 task_exit.go:221] [   2:   2:] Transitioning from exit state TaskExitNone to TaskExitInitiated
fatal error: unexpected signal during runtime execution
[signal SIGFPE: floating-point exception code=0x6 addr=0x425ea5 pc=0x425ea5]

goroutine 23 [running]:
runtime.throw(0x1203782, 0x2a)
	GOROOT/src/runtime/panic.go:1116 +0x72 fp=0xc0000bf630 sp=0xc0000bf600 pc=0x437672

```
