### ISSUE TITLE
 Invalid request partialResult true and err (type syscall.Errno) invalid argument for write operation on "/proc/sys/net/ipv4/tcp_rmem"

### ISSUE THREAD

**Issue by dqminh** [google/gvisor#5854]
**Description**

We run syzkaller for gvisor internally, and the following C program generate a traceback

Traceback

```
W0419 14:33:22.797083       1 log.go:329] Invalid request partialResult true and err (type syscall.Errno) invalid argument for write operation on "/proc/sys/ne
t/ipv4/tcp_rmem", *proc.tcpMemFile:
goroutine 38 [running]:
gvisor.dev/gvisor/pkg/log.Stacks(0x7aea00, 0x1c0bd90, 0x0, 0xc00052b948)
        pkg/log/log.go:313 +0xa8
gvisor.dev/gvisor/pkg/log.Traceback(0x129db9f, 0x50, 0xc00033a900, 0x6, 0x6)
        pkg/log/log.go:328 +0x2a
gvisor.dev/gvisor/pkg/sentry/syscalls/linux.handleIOError(0x13edf80, 0xc000514000, 0x13e8a01, 0x13be0a0, 0x1bbab10, 0x13bdec0, 0x139f590, 0x1260795, 0x5, 0xc00
0500a50, ...)
        pkg/sentry/syscalls/linux/error.go:68 +0x293
gvisor.dev/gvisor/pkg/sentry/syscalls/linux.Write(0xc000514000, 0x3, 0x20000000, 0x48, 0x15, 0x7fea63c00ad6, 0x0, 0x0, 0x0, 0x0, ...)
        pkg/sentry/syscalls/linux/sys_write.go:74 +0x29e
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).executeSyscall(0xc000514000, 0x1, 0x3, 0x20000000, 0x48, 0x15, 0x7fea63c00ad6, 0x0, 0xe22f0c, 0x125e0c0, ...)
        pkg/sentry/kernel/task_syscall.go:104 +0x13c
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallInvoke(0xc000514000, 0x1, 0x3, 0x20000000, 0x48, 0x15, 0x7fea63c00ad6, 0x0, 0x7fea63c00ad6, 0x0)
        pkg/sentry/kernel/task_syscall.go:239 +0x66
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscallEnter(0xc000514000, 0x1, 0x3, 0x20000000, 0x48, 0x15, 0x7fea63c00ad6, 0x0, 0x0, 0x0)
        pkg/sentry/kernel/task_syscall.go:199 +0x98
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).doSyscall(0xc000514000, 0x2, 0xc000514000)
        pkg/sentry/kernel/task_syscall.go:174 +0x15c
gvisor.dev/gvisor/pkg/sentry/kernel.(*runApp).execute(0x0, 0xc000514000, 0x13bbe00, 0x0)
        pkg/sentry/kernel/task_run.go:282 +0xc45
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).run(0xc000514000, 0x1)
        pkg/sentry/kernel/task_run.go:97 +0x1af
created by gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).Start
        pkg/sentry/kernel/task_start.go:328 +0xfe

```

Reproducer:

```
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
                syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
        syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
        syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
                                intptr_t res = 0;
memcpy((void*)0x20000100, "/proc/sys/net/ipv4/tcp_rmem\000", 28);
        res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000100ul, 1ul, 0ul);
        if (res != -1)
                r[0] = res;
sprintf((char*)0x20000000, "%023llo", (long long)7);
*(uint8_t*)0x20000017 = 0x20;
sprintf((char*)0x20000018, "%023llo", (long long)4);
*(uint8_t*)0x2000002f = 0x20;
sprintf((char*)0x20000030, "%023llo", (long long)9);
*(uint8_t*)0x20000047 = 0;
        syscall(__NR_write, r[0], 0x20000000ul, 0x48ul);
        return 0;
}
```

**Steps to reproduce**

```
gcc -static -pthread -o repro main.c
mkdir -p bundle
$EDITOR bundle/config.json # content as follow
sudo ./runsc -debug-log=$(pwd)/debug.log -debug -strace -platform=kvm -network=none -overlay -net-raw -watchdog-action=panic -TESTONLY-unsafe-nonroot run -bundle ./bundle syzkaller
```

With config.json as

```
{
        "root": {
                "path": "DIR_WITH_REPRO_BIN",
                "readonly": true
        },
        "process":{
                "args": ["/repro"],
                "cwd": "/tmp"
        }
}
```

**Environment**

```
I0419 14:39:07.301690   40430 main.go:211] ***************************
I0419 14:39:07.301836   40430 main.go:212] Args: [./runsc1 -debug-log=/home/dqminh/workspace/fuzz-gvisor/debug1.log -debug -strace -platform=kvm -network=none -overlay -net-raw -watchdog-action=panic -TESTONLY-unsafe-nonroot run -bundle ./bundle syzkaller]
I0419 14:39:07.301914   40430 main.go:213] Version release-20210408.0-32-g108410638aa8
I0419 14:39:07.301948   40430 main.go:214] GOOS: linux
I0419 14:39:07.301980   40430 main.go:215] GOARCH: amd64
I0419 14:39:07.302011   40430 main.go:216] PID: 40430
I0419 14:39:07.302045   40430 main.go:217] UID: 0, GID: 0
I0419 14:39:07.302078   40430 main.go:218] Configuration:
I0419 14:39:07.302110   40430 main.go:219]              RootDir: /var/run/runsc
I0419 14:39:07.302155   40430 main.go:220]              Platform: kvm
I0419 14:39:07.302189   40430 main.go:221]              FileAccess: 0, overlay: true
I0419 14:39:07.302227   40430 main.go:222]              Network: 2, logging: false
I0419 14:39:07.302274   40430 main.go:223]              Strace: true, max size: 1024, syscalls:
I0419 14:39:07.302309   40430 main.go:224]              VFS2 enabled: false
I0419 14:39:07.302341   40430 main.go:225] ***************************
```

**Comment by prattmic** [comment]
This should probably get fixed either way, but I wonder if this still reproduces if you enable vfs2?

**Comment by ayushr2** [comment]
I can confirm that this is no longer reproducible.
