### ISSUE TITLE
HostFileMapper.RegenerateMappings trips over seccomp rules

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#6116]
From Kent McDonough

**Description**

gVisor produces a syscall from a containerized program that violates its own seccomp profile and terminates the container
Following output is logged through journald:

```
May 28 15:37:13 casper audit[8148]: SECCOMP auid=4294967295 uid=65534 gid=65534 ses=4294967295 subj=unconfined pid=8148 comm="exe" exe="/usr/bin/runsc" sig=31 arch=c000003e syscall=9 compat=0 ip=0x48748a code=0x80000000
May 28 15:37:13 casper kernel: audit: type=1326 audit(1622230633.972:58): auid=4294967295 uid=65534 gid=65534 ses=4294967295 subj=unconfined pid=8148 comm="exe" exe="/usr/bin/runsc" sig=31 arch=c000003e syscall=9 compat=0 ip=0x48748a code=0x80000000
```

**Steps to reproduce**

Compile and run the following program from within a container

```
#include <stdio.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/syscall.h>

int main() {
 //open(&(0x7f0000000000)='/lib/x86_64-linux-gnu/libc.so.6\x00', 0x680002, 0x20)
  int result = syscall(SYS_open, "/lib/x86_64-linux-gnu/libc.so.6", 0x680002, 0x20);
  printf("result was %d\n", result);
}
```

**Environment**

Please include the following details of your environment:

*   `runsc -version`
```
runsc version release-20210322.0
spec: 1.0.2
```
*   `docker version` or `docker info` (if available)
```
Client: Docker Engine - Community
 Version:       20.10.5
 API version:   1.41
 Go version:    go1.13.15
 Git commit:    55c4c88
 Built:         Tue Mar  2 20:18:20 2021
 OS/Arch:       linux/amd64
 Context:       default
 Experimental:  true

Server: Docker Engine - Community
 Engine:
  Version:      20.10.5
  API version:  1.41 (minimum version 1.12)
  Go version:   go1.13.15
  Git commit:   363e9a8
  Built:        Tue Mar  2 20:16:15 2021
  OS/Arch:      linux/amd64
  Experimental: false
 containerd:
  Version:      1.4.4
  GitCommit:    05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:      1.0.0-rc93
  GitCommit:    12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:      0.19.0
  GitCommit:    de40ad0
```

*   `uname -a`
```
Linux casper 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

*   `runsc` debug logs (if available)
don't have these on hand, but I can retrieve them if necessary

**Comment by fvoznika** [comment]
Repro:
```
gcc -Wall -Werror gvisor-open.c -o gvisor-open
docker run --rm --runtime=runsc --v "$(pwd)":/repro ubuntu /repro/gvisor-open
```

Here is the offending stack:
```
goroutine 81 [syscall]:
syscall.Syscall6(0x9, 0x7fd328779000, 0x200000, 0x1, 0x11, 0x10, 0x0, 0x0, 0x0, 0x0)
        third_party/go/gc/src/syscall/asm_linux_amd64.s:43 +0x5 fp=0xc0005b53e8 sp=0xc0005b53e0 pc=0x48c745
google3/third_party/gvisor/pkg/sentry/fs/fsutil/fsutil.(*HostFileMapper).RegenerateMappings(0xc000097560, 0x10, 0x0, 0x0
)
        third_party/gvisor/pkg/sentry/fs/fsutil/host_file_mapper.go:241 +0x14e fp=0xc0005b54c0 sp=0xc0005b53e8 pc=0x878c
8e
google3/third_party/gvisor/pkg/sentry/fs/fsutil/fsutil.(*CachingInodeOperations).NotifyChangeFD(0xc0005c6400, 0x0, 0x0)
        third_party/gvisor/pkg/sentry/fs/fsutil/inode_cached.go:981 +0x65 fp=0xc0005b5508 sp=0xc0005b54c0 pc=0x880ae5
google3/third_party/gvisor/pkg/sentry/fs/gofer/gofer.(*inodeFileState).getHandles(0xc0005b8d10, 0x14a9220, 0xc0001ec000,
 0x1010000000000, 0x1000000, 0xc0005c6400, 0xb0, 0x7fd36a4814e8, 0x30)
        third_party/gvisor/pkg/sentry/fs/gofer/inode.go:190 +0x1ff fp=0xc0005b55b8 sp=0xc0005b5508 pc=0xc4bcdf
google3/third_party/gvisor/pkg/sentry/fs/gofer/gofer.(*inodeOperations).getFileDefault(0xc000097580, 0x14a9220, 0xc0001e
c000, 0xc0005b93f0, 0x1010000000000, 0x1000000, 0x1255520, 0x0, 0x0)
        third_party/gvisor/pkg/sentry/fs/gofer/inode.go:545 +0x69 fp=0xc0005b5620 sp=0xc0005b55b8 pc=0xc4e449
google3/third_party/gvisor/pkg/sentry/fs/gofer/gofer.(*inodeOperations).GetFile(0xc000097580, 0x14a9220, 0xc0001ec000, 0
xc0005b93f0, 0x1010000000000, 0x1000000, 0x9, 0xc0005b56e8, 0xc0005b93f0)
        third_party/gvisor/pkg/sentry/fs/gofer/inode.go:485 +0x139 fp=0xc0005b5678 sp=0xc0005b5620 pc=0xc4da19
google3/third_party/gvisor/pkg/sentry/fs/fs.(*Inode).GetFile(0xc0005c6800, 0x14a9220, 0xc0001ec000, 0xc0005b93f0, 0x1010
000000000, 0x1000000, 0xc0001ec000, 0xc0005b8e70, 0x0)
        third_party/gvisor/pkg/sentry/fs/inode.go:249 +0x111 fp=0xc0005b56d0 sp=0xc0005b5678 pc=0x820811
google3/third_party/gvisor/pkg/sentry/fs/fs.overlayFile(0x14a9220, 0xc0001ec000, 0xc0005c6800, 0x1010000000000, 0x100000
0, 0x14a9220, 0xc0001ec000, 0x101)
        third_party/gvisor/pkg/sentry/fs/file_overlay.go:52 +0xaa fp=0xc0005b5748 sp=0xc0005b56d0 pc=0x81b16a
google3/third_party/gvisor/pkg/sentry/fs/fs.overlayGetFile(0x14a9220, 0xc0001ec000, 0xc0005bc3c0, 0xc0005b8e70, 0x101000
0000000, 0x1000000, 0xc000000101, 0x0, 0x0)
        third_party/gvisor/pkg/sentry/fs/inode_overlay.go:505 +0xaf fp=0xc0005b57e0 sp=0xc0005b5748 pc=0x825b6f
google3/third_party/gvisor/pkg/sentry/fs/fs.(*Inode).GetFile(0xc0005c6c00, 0x14a9220, 0xc0001ec000, 0xc0005b8e70, 0x1010
000000000, 0x1000000, 0xc, 0xc0005b59b8, 0xc0005b8e70)
        third_party/gvisor/pkg/sentry/fs/inode.go:246 +0x6d fp=0xc0005b5838 sp=0xc0005b57e0 pc=0x82076d
google3/third_party/gvisor/pkg/sentry/syscalls/linux/linux.openAt.func1(0xc0003668f0, 0xc0005b8e70, 0x26, 0x0, 0x0)
        third_party/gvisor/pkg/sentry/syscalls/linux/sys_file.go:177 +0x27b fp=0xc0005b5960 sp=0xc0005b5838 pc=0xaa04db
google3/third_party/gvisor/pkg/sentry/syscalls/linux/linux.fileOpOn(0xc0001ec000, 0x5603ffffff9c, 0xc00007d300, 0x1f, 0x
1, 0xc0005b5a80, 0x0, 0x0)
        third_party/gvisor/pkg/sentry/syscalls/linux/sys_file.go:112 +0x1eb fp=0xc0005b5a40 sp=0xc0005b5960 pc=0xa6462b
google3/third_party/gvisor/pkg/sentry/syscalls/linux/linux.openAt(0xc0001ec000, 0xffffff9c, 0x5603522337d8, 0x680002, 0x
0, 0xc000357080, 0x300000002)
        third_party/gvisor/pkg/sentry/syscalls/linux/sys_file.go:143 +0x115 fp=0xc0005b5ab8 sp=0xc0005b5a40 pc=0xa64af5
google3/third_party/gvisor/pkg/sentry/syscalls/linux/linux.Open(0xc0001ec000, 0x5603522337d8, 0x680002, 0x20, 0x0, 0x7f1
d55a76d50, 0x7f9edcbf2e20, 0x3d, 0x68c8, 0xc0005b5bf4, ...)
        third_party/gvisor/pkg/sentry/syscalls/linux/sys_file.go:473 +0xb7 fp=0xc0005b5b08 sp=0xc0005b5ab8 pc=0xa650d7
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).executeSyscall(0xc0001ec000, 0x2, 0x5603522337d8, 0x680002, 
0x20, 0x0, 0x7f1d55a76d50, 0x7f9edcbf2e20, 0x1, 0x12f9300, ...)
        third_party/gvisor/pkg/sentry/kernel/task_syscall.go:102 +0x13c fp=0xc0005b5c68 sp=0xc0005b5b08 pc=0xa1a39c
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).doSyscallInvoke(0xc0001ec000, 0x2, 0x5603522337d8, 0x680002, 0x20, 0x0, 0x7f1d55a76d50, 0x7f9edcbf2e20, 0x7f1d55a76d50, 0x7f9edcbf2e20)
        third_party/gvisor/pkg/sentry/kernel/task_syscall.go:237 +0x66 fp=0xc0005b5cf0 sp=0xc0005b5c68 pc=0xa1b566
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).doSyscallEnter(0xc0001ec000, 0x2, 0x5603522337d8, 0x680002, 0x20, 0x0, 0x7f1d55a76d50, 0x7f9edcbf2e20, 0xe80b45, 0xc0001c6408)
        third_party/gvisor/pkg/sentry/kernel/task_syscall.go:197 +0x98 fp=0xc0005b5d50 sp=0xc0005b5cf0 pc=0xa1b118
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).doSyscall(0xc0001ec000, 0x2, 0xc0001ec000)
        third_party/gvisor/pkg/sentry/kernel/task_syscall.go:172 +0x15c fp=0xc0005b5e20 sp=0xc0005b5d50 pc=0xa1aabc
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*runApp).execute(0x0, 0xc0001ec000, 0x147cd20, 0x0)
        third_party/gvisor/pkg/sentry/kernel/task_run.go:282 +0xca5 fp=0xc0005b5f60 sp=0xc0005b5e20 pc=0xa0ee25
google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).run(0xc0001ec000, 0x1)
        third_party/gvisor/pkg/sentry/kernel/task_run.go:97 +0x1af fp=0xc0005b5fd0 sp=0xc0005b5f60 pc=0xa0da8f
runtime.goexit()
        third_party/go/gc/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0005b5fd8 sp=0xc0005b5fd0 pc=0x475a61
created by google3/third_party/gvisor/pkg/sentry/kernel/kernel.(*Task).Start
        third_party/gvisor/pkg/sentry/kernel/task_start.go:328 +0xfe
```

**Comment by ianlewis** [comment]
Hmm, Do we know what options runsc it was run with?

**Comment by nixprime** [comment]
It looks like we're just missing a filter for `MAP_SHARED|MAP_FIXED`?

**Comment by ianlewis** [comment]
Yeah. as long as we're comfortable with that
https://cs.opensource.google/gvisor/gvisor/+/master:runsc/boot/filter/config.go;l=192-229
