### ISSUE TITLE
panics on invalid command line arguments

### ISSUE THREAD

**Issue by dvyukov** [google/gvisor#66]
I am probably doing something wrong due to lack of documentation, but please don't be python :)
More readable explanation of what I am doing wrong would be helpful. I am on ba426f7782d35f971820a0193cfda58485b92cad.

```
$ runsc -debug -root=. exec --process ./process.json  123
I0613 13:04:48.375038  108241 x:0] ***************************
I0613 13:04:48.375096  108241 x:0] Args: [runsc -debug -root=. exec --process ./process.json 123]
I0613 13:04:48.375123  108241 x:0] Git Revision: ba426f7782d35f971820a0193cfda58485b92cad
I0613 13:04:48.375127  108241 x:0] PID: 108241
I0613 13:04:48.375147  108241 x:0] UID: 129372, GID: 89939
I0613 13:04:48.375165  108241 x:0] Configuration:
I0613 13:04:48.375170  108241 x:0] 		RootDir: .
I0613 13:04:48.375174  108241 x:0] 		Platform: ptrace
I0613 13:04:48.375190  108241 x:0] 		FileAccess: proxy, overlay: false
I0613 13:04:48.375197  108241 x:0] 		Network: sandbox, logging: false
I0613 13:04:48.375204  108241 x:0] 		Strace: false, max size: 1024, syscalls: []
I0613 13:04:48.375209  108241 x:0] ***************************
D0613 13:04:48.375334  108241 x:0] Load container "." "123"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa07342]

goroutine 1 [running]:
gvisor.googlesource.com/gvisor/runsc/cmd.(*Exec).Execute(0xc4201dc3f0, 0xc8e820, 0xc4200380c8, 0xc4200de480, 0xc42000be80, 0x2, 0x2, 0xa97400)
	runsc/cmd/exec.go:139 +0x2b2
github.com/google/subcommands.(*Commander).Execute(0xc42002e0e0, 0xc8e820, 0xc4200380c8, 0xc42000be80, 0x2, 0x2, 0xc42000be80)
	external/com_github_google_subcommands/subcommands.go:141 +0x29f
github.com/google/subcommands.Execute(0xc8e820, 0xc4200380c8, 0xc42000be80, 0x2, 0x2, 0x5)
	external/com_github_google_subcommands/subcommands.go:371 +0x5f
main.main()
	runsc/main.go:188 +0xfda
```

```
$ runsc -debug -root=. run --bundle ./123 234
I0613 13:08:32.103834  109345 x:0] ***************************
I0613 13:08:32.103886  109345 x:0] Args: [runsc -debug -root=. run --bundle ./123 234]
I0613 13:08:32.103910  109345 x:0] Git Revision: ba426f7782d35f971820a0193cfda58485b92cad
I0613 13:08:32.103917  109345 x:0] PID: 109345
I0613 13:08:32.103937  109345 x:0] UID: 129372, GID: 89939
I0613 13:08:32.103941  109345 x:0] Configuration:
I0613 13:08:32.103957  109345 x:0] 		RootDir: .
I0613 13:08:32.103962  109345 x:0] 		Platform: ptrace
I0613 13:08:32.103972  109345 x:0] 		FileAccess: proxy, overlay: false
I0613 13:08:32.103979  109345 x:0] 		Network: sandbox, logging: false
I0613 13:08:32.103986  109345 x:0] 		Strace: false, max size: 1024, syscalls: []
I0613 13:08:32.103996  109345 x:0] ***************************
D0613 13:08:32.104152  109345 x:0] Run container "234" in root dir: .
D0613 13:08:32.104166  109345 x:0] Create container "234" in root dir: .
D0613 13:08:32.104292  109345 x:0] Starting gofer: /usr/local/bin/runsc [--root=. --debug=true --log= --log-format=text --debug-log-dir= --file-access=proxy --overlay=false --network=sandbox --log-packets=false --platform=ptrace --strace=false --strace-syscalls= --strace-log-size=1024 gofer --bundle ./123 --io-fds=3]
I0613 13:08:32.104877  109345 x:0] Gofer started, pid: 109351
I0613 13:08:32.104962  109345 x:0] Sandbox will be started in new IPC and UTS namespaces
I0613 13:08:32.104971  109345 x:0] Sandbox will be started in the current PID namespace
I0613 13:08:32.104980  109345 x:0] Sandbox will be started in new mount namespace
I0613 13:08:32.104986  109345 x:0] Sandbox will be started in new network namespace
I0613 13:08:32.104991  109345 x:0] Sandbox will be started in new user namespace
D0613 13:08:32.104994  109345 x:0] Starting sandbox: /usr/local/bin/runsc [/usr/local/bin/runsc --root=. --debug=true --log= --log-format=text --debug-log-dir= --file-access=proxy --overlay=false --network=sandbox --log-packets=false --platform=ptrace --strace=false --strace-syscalls= --strace-log-size=1024 boot --bundle ./123 --controller-fd=3 --console=false --io-fds=4]
I0613 13:08:32.108793  109345 x:0] Sandbox started, pid: 109356
D0613 13:08:32.108826  109345 x:0] Waiting for sandbox "234" creation
I0613 13:08:32.113569  109356 x:0] ***************************
I0613 13:08:32.113613  109356 x:0] Args: [/usr/local/bin/runsc --root=. --debug=true --log= --log-format=text --debug-log-dir= --file-access=proxy --overlay=false --network=sandbox --log-packets=false --platform=ptrace --strace=false --strace-syscalls= --strace-log-size=1024 boot --bundle ./123 --controller-fd=3 --console=false --io-fds=4]
I0613 13:08:32.113628  109356 x:0] Git Revision: ba426f7782d35f971820a0193cfda58485b92cad
I0613 13:08:32.113634  109356 x:0] PID: 109356
I0613 13:08:32.113640  109356 x:0] UID: 65534, GID: 65534
I0613 13:08:32.113645  109356 x:0] Configuration:
I0613 13:08:32.113653  109356 x:0] 		RootDir: .
I0613 13:08:32.113657  109356 x:0] 		Platform: ptrace
I0613 13:08:32.113668  109356 x:0] 		FileAccess: proxy, overlay: false
I0613 13:08:32.113674  109356 x:0] 		Network: sandbox, logging: false
I0613 13:08:32.113680  109356 x:0] 		Strace: false, max size: 1024, syscalls: []
I0613 13:08:32.113684  109356 x:0] ***************************
D0613 13:08:32.113794  109356 x:0] Spec: &{Version: Process:0xc420103d40 Root:<nil> Hostname: Mounts:[] Hooks:<nil> Annotations:map[] Linux:<nil> Solaris:<nil> Windows:<nil>}
D0613 13:08:32.113814  109356 x:0] Spec.Hooks: <nil>
D0613 13:08:32.113818  109356 x:0] Spec.Linux: <nil>
D0613 13:08:32.113823  109356 x:0] Spec.Process: &{Terminal:true ConsoleSize:<nil> User:{UID:0 GID:0 AdditionalGids:[] Username:} Args:[sleep 5] Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin TERM=xterm] Cwd:/ Capabilities:<nil> Rlimits:[] NoNewPrivileges:false ApparmorProfile: OOMScoreAdj:<nil> SelinuxLabel:}
D0613 13:08:32.113845  109356 x:0] Spec.Root: <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0413c]

goroutine 1 [running]:
gvisor.googlesource.com/gvisor/runsc/cmd.(*Boot).Execute(0xc420134740, 0xc8e820, 0xc420108010, 0xc42011a3c0, 0xc420119e40, 0x2, 0x2, 0x0)
	runsc/cmd/boot.go:96 +0x17c
github.com/google/subcommands.(*Commander).Execute(0xc42011c000, 0xc8e820, 0xc420108010, 0xc420119e40, 0x2, 0x2, 0xc420119e40)
	external/com_github_google_subcommands/subcommands.go:141 +0x29f
github.com/google/subcommands.Execute(0xc8e820, 0xc420108010, 0xc420119e40, 0x2, 0x2, 0x5)
	external/com_github_google_subcommands/subcommands.go:371 +0x5f
main.main()
	runsc/main.go:188 +0xfda

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	GOROOT/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	GOROOT/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	GOROOT/src/os/signal/signal_unix.go:28 +0x41
D0613 13:08:32.172677  109345 x:0] Destroy container "234"
W0613 13:08:32.172712  109345 x:0] FATAL ERROR: error running container: error creating container: unexpected error waiting for sandbox "234", err: process (109356) is not running, err: <nil>
error running container: error creating container: unexpected error waiting for sandbox "234", err: process (109356) is not running, err: <nil>
```

**Comment by dvyukov** [comment]
On a related note, is there an example of how to run something with gvisor (I don't mean docker!).

**Comment by dvyukov** [comment]
And another one:

```
$ /usr/local/bin/runsc -root=root -network=none  run --bundle ./templ 12
I0613 16:05:56.663918   65296 x:0] ***************************
I0613 16:05:56.663975   65296 x:0] Args: [/usr/local/bin/runsc -root=root -network=none run --bundle ./templ 12]
I0613 16:05:56.663998   65296 x:0] Git Revision: ba426f7782d35f971820a0193cfda58485b92cad-dirty
I0613 16:05:56.664005   65296 x:0] PID: 65296
I0613 16:05:56.664025   65296 x:0] UID: 129372, GID: 89939
I0613 16:05:56.664029   65296 x:0] Configuration:
I0613 16:05:56.664045   65296 x:0] 		RootDir: root
I0613 16:05:56.664076   65296 x:0] 		Platform: ptrace
I0613 16:05:56.664093   65296 x:0] 		FileAccess: proxy, overlay: false
I0613 16:05:56.664100   65296 x:0] 		Network: none, logging: false
I0613 16:05:56.664125   65296 x:0] 		Strace: false, max size: 1024, syscalls: []
I0613 16:05:56.664134   65296 x:0] ***************************
I0613 16:05:56.664804   65296 x:0] Gofer started, pid: 65301
I0613 16:05:56.664864   65296 x:0] Sandbox will be started in new IPC and UTS namespaces
I0613 16:05:56.664871   65296 x:0] Sandbox will be started in the current PID namespace
I0613 16:05:56.664880   65296 x:0] Sandbox will be started in new mount namespace
I0613 16:05:56.664889   65296 x:0] Sandbox will be started in new network namespace
I0613 16:05:56.664896   65296 x:0] Sandbox will be started in new user namespace
I0613 16:05:56.667426   65296 x:0] Sandbox started, pid: 65306
I0613 16:05:56.672422   65306 x:0] ***************************
I0613 16:05:56.672464   65306 x:0] Args: [/usr/local/bin/runsc --root=root --debug=false --log= --log-format=text --debug-log-dir= --file-access=proxy --overlay=false --network=none --log-packets=false --platform=ptrace --strace=false --strace-syscalls= --strace-log-size=1024 boot --bundle ./templ --controller-fd=3 --console=false --io-fds=4]
I0613 16:05:56.672478   65306 x:0] Git Revision: ba426f7782d35f971820a0193cfda58485b92cad-dirty
I0613 16:05:56.672484   65306 x:0] PID: 65306
I0613 16:05:56.672490   65306 x:0] UID: 65534, GID: 65534
I0613 16:05:56.672496   65306 x:0] Configuration:
I0613 16:05:56.672500   65306 x:0] 		RootDir: root
I0613 16:05:56.672504   65306 x:0] 		Platform: ptrace
I0613 16:05:56.672515   65306 x:0] 		FileAccess: proxy, overlay: false
I0613 16:05:56.672521   65306 x:0] 		Network: none, logging: false
I0613 16:05:56.672527   65306 x:0] 		Strace: false, max size: 1024, syscalls: []
I0613 16:05:56.672532   65306 x:0] ***************************
I0613 16:05:56.672677   65306 x:0] Platform: ptrace
panic: runtime error: index out of range

goroutine 1 [running]:
gvisor.googlesource.com/gvisor/runsc/boot.New(0xc42011d490, 0xc4202123c0, 0x3, 0xc420109bc8, 0x1, 0x1, 0xc420253b00, 0x4df047, 0x5, 0xc420101a10)
	runsc/boot/loader.go:156 +0x1aff
gvisor.googlesource.com/gvisor/runsc/cmd.(*Boot).Execute(0xc420134740, 0xc8e840, 0xc420108010, 0xc42011a420, 0xc420119e40, 0x2, 0x2, 0x0)
	runsc/cmd/boot.go:130 +0x879
github.com/google/subcommands.(*Commander).Execute(0xc42011c000, 0xc8e840, 0xc420108010, 0xc420119e40, 0x2, 0x2, 0xc420119e40)
	external/com_github_google_subcommands/subcommands.go:141 +0x29f
github.com/google/subcommands.Execute(0xc8e840, 0xc420108010, 0xc420119e40, 0x2, 0x2, 0x5)
	external/com_github_google_subcommands/subcommands.go:371 +0x5f
main.main()
	runsc/main.go:188 +0xfda

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	GOROOT/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	GOROOT/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	GOROOT/src/os/signal/signal_unix.go:28 +0x41

goroutine 19 [chan receive, locked to thread]:
gvisor.googlesource.com/gvisor/pkg/sentry/platform/ptrace.newSubprocess.func1(0xbf9178, 0xc4200fc120, 0xc42017e2a0, 0xc4200fc180)
	pkg/sentry/platform/ptrace/subprocess.go:173 +0x16b
created by gvisor.googlesource.com/gvisor/pkg/sentry/platform/ptrace.newSubprocess
	pkg/sentry/platform/ptrace/subprocess.go:148 +0x156

goroutine 20 [semacquire]:
sync.runtime_notifyListWait(0xc420125f10, 0xc400000000)
	GOROOT/src/runtime/sema.go:510 +0x10b
sync.(*Cond).Wait(0xc420125f00)
	GOROOT/src/sync/cond.go:56 +0x80
gvisor.googlesource.com/gvisor/pkg/sentry/platform/filemem.(*FileMem).findReclaimable(0xc420125b00, 0x0, 0x0, 0x0)
	pkg/sentry/platform/filemem/filemem.go:427 +0x83
gvisor.googlesource.com/gvisor/pkg/sentry/platform/filemem.(*FileMem).runReclaim(0xc420125b00)
	pkg/sentry/platform/filemem/filemem.go:371 +0x67
created by gvisor.googlesource.com/gvisor/pkg/sentry/platform/filemem.newFromFile
	pkg/sentry/platform/filemem/filemem.go:189 +0x16d

goroutine 22 [select]:
gvisor.googlesource.com/gvisor/pkg/sentry/kernel.(*Timekeeper).startUpdater.func1(0xc42011a5a0, 0xc42010e640)
	pkg/sentry/kernel/timekeeper.go:208 +0x18f
created by gvisor.googlesource.com/gvisor/pkg/sentry/kernel.(*Timekeeper).startUpdater
	pkg/sentry/kernel/timekeeper.go:176 +0xcb
W0613 16:05:56.795662   65296 x:0] FATAL ERROR: error running container: error creating container: unexpected error waiting for sandbox "12", err: process (65306) is not running, err: <nil>
error running container: error creating container: unexpected error waiting for sandbox "12", err: process (65306) is not running, err: <nil>
```

**Comment by fvoznika** [comment]
We're doing pretty much no validation on the input, so as you've seen, it's fairly easy to make it panic with invalid parameters. We'll improve it...

As for what it's needed, --bundle expects a directory with a file called `config.json`. This file must contain a JSON [spec](https://github.com/opencontainers/runtime-spec/blob/695b81699f3980e8743099451a04cddb5377afdb/specs-go/config.go#L6) that configures the container you want to run inside gVisor. For a minimal configuration, you can see how the unit tests sets it up [here](https://github.com/google/gvisor/blob/master/runsc/container/container_test.go).

Network requires a bit more setup, as it needs a network namespace with a veth inside it. Or you can use `--network=host` when you can `runsc create`. I can give you more details if you're interested.

**Comment by dvyukov** [comment]
Thanks, @fvoznika! The spec link is useful.
