### ISSUE TITLE
Container exits with IO exception

### ISSUE THREAD

**Issue by srikrsna-buf** [google/gvisor#6796]
### Description

Container exits with IO exception while running on `runsc`. Runs normally on `runc`. It is a Java program and gives the following exception

```stack
Exception in thread "main" java.io.IOException: Attempted to run proto extension generator as protoc plugin, but could not read
CodeGeneratorRequest.
        at io.grpc.kotlin.generator.protoc.AbstractGeneratorRunner.mainAsProtocPlugin(AbstractGeneratorRunner.kt:43)
        at io.grpc.kotlin.generator.protoc.AbstractGeneratorRunner.doMain(AbstractGeneratorRunner.kt:87)
        at io.grpc.kotlin.generator.GeneratorRunner.main(GeneratorRunner.kt:28)
Caused by: java.io.IOException: Illegal seek
        at java.base/java.io.FileInputStream.available0(Native Method)
        at java.base/java.io.FileInputStream.available(FileInputStream.java:330)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:359)
        at com.google.protobuf.CodedInputStream$StreamDecoder.tryRefillBuffer(CodedInputStream.java:2785)
        at com.google.protobuf.CodedInputStream$StreamDecoder.isAtEnd(CodedInputStream.java:2708)
        at com.google.protobuf.CodedInputStream$StreamDecoder.readTag(CodedInputStream.java:2059)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest.<init>(PluginProtos.java:1244)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest.<init>(PluginProtos.java:1203)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest$1.parsePartialFrom(PluginProtos.java:3019)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest$1.parsePartialFrom(PluginProtos.java:3013)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:215)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:232)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:237)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:339)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest.parseFrom(PluginProtos.java:1753)
        at io.grpc.kotlin.generator.protoc.AbstractGeneratorRunner.mainAsProtocPlugin(AbstractGeneratorRunner.kt:40)
        ... 2 more
```

### Steps to reproduce

- `docker pull skrsnabuf/protoc-gen-grpc-kotlin`
- `docker run --runtime runsc -i skrsnabuf/protoc-gen-grpc-kotlin` and press enter (throws the exception)
- `docker run -i skrsnabuf/protoc-gen-grpc-kotlin` waits for stdin to complete/termination as it should

Dockerfile
```dockerfile
FROM debian:buster as build
ARG VERSION=1.2.0
WORKDIR /app
RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://search.maven.org/remotecontent?filepath=io/grpc/protoc-gen-grpc-kotlin/${VERSION}/protoc-gen-grpc-kotlin-${VERSION}-jdk7.jar -o protoc-gen-grpc-kotlin-jdk7.jar

FROM openjdk:jre-slim
WORKDIR /app
COPY --from=build /app/protoc-gen-grpc-kotlin-jdk7.jar .
COPY plugins/protoc-gen-grpc-kotlin.sh .
RUN chmod +x ./protoc-gen-grpc-kotlin.sh
ENTRYPOINT [ "/app/protoc-gen-grpc-kotlin.sh" ]
```

protoc-gen-grpc-kotlin.sh
```sh
#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
java -jar $DIR/protoc-gen-grpc-kotlin-jdk7.jar "$@"
```

### runsc version

```shell
runsc version release-20211019.0
spec: 1.0.2
```

### docker version (if using docker)

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)
Server:
 Containers: 14
  Running: 4
  Paused: 0
  Stopped: 10
 Images: 37
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runsc runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-18-cloud-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.67GiB
 Name: outline
 ID: RY4W:MZ23:F2MY:DVLM:LYMU:5KLK:A4HL:RNCG:PP2G:ARBK:65C3:VJDX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: skrsnabuf
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
WARNING: No swap limit support
```

### uname

Linux outline 4.19.0-18-cloud-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

**Comment by fvoznika** [comment]
Thanks for the detailed repro. This fails because we don't implement `ioctl(2)` for host FDs, mostly to reduce the attack surface that gets exposed from the host. Here is the sequence of calls:

```
I1102 11:05:15.691419  898344 strace.go:629] [   5:   6] java X read(0x0 host:[1], 0x7fa2a89bff30 "\n", 0x2000) = 1 (0x1) (3.180166845s)   ===> HIT ENTER
I1102 11:05:15.691629  898344 strace.go:588] [   5:   6] java E fstat(0x0 host:[1], 0x7fa2a89c1fb0)
I1102 11:05:15.691707  898344 strace.go:626] [   5:   6] java X fstat(0x0 host:[1], 0x7fa2a89c1fb0 {dev=7, ino=1, mode=S_IFIFO|0o600, nlink=1, uid=0, gid=0, rdev=0, size=0, blksize=4096, blocks=0, atime=2021-11-02 11:05:15.686472357 -0700 PDT, mtime=2021-11-02 11:05:15.686472357 -0700 PDT, ctime=2021-11-02 11:05:15.686472357 -0700 PDT}) = 0 (0x0) (18.363µs)
I1102 11:05:15.691788  898344 strace.go:591] [   5:   6] java E ioctl(0x0 host:[1], 0x541b, 0x7fa2a89c1fac)
I1102 11:05:15.691811  898344 strace.go:629] [   5:   6] java X ioctl(0x0 host:[1], 0x541b, 0x7fa2a89c1fac) = 0 (0x0) errno=25 (not a typewriter) (1.847µs)   ===> IOCTL FAILS SO IT FALLS BACK TO lseek(stdin, 0, SEEK_CUR)
I1102 11:05:15.691866  898344 strace.go:591] [   5:   6] java E lseek(0x0, 0x0, 0x1)
I1102 11:05:15.691885  898344 strace.go:629] [   5:   6] java X lseek(0x0, 0x0, 0x1) = 0 (0x0) errno=29 (illegal seek) (1.873µs)
```
Here is an example after `ioctl(fd, FIONREAD)` is implemented for host FDs:
```
I1102 13:13:57.394866  1048149 strace.go:629] [   5:   6] java X read(0x0 host:[1], 0x7fc23b7ccf30 "\n", 0x2000) = 1 (0x1) (16.56µs)  ===> HIT ENTER
I1102 13:13:57.394937  1048149 strace.go:588] [   5:   6] java E fstat(0x0 host:[1], 0x7fc23b7cefb0)
I1102 13:13:57.394992  1048149 strace.go:626] [   5:   6] java X fstat(0x0 host:[1], 0x7fc23b7cefb0 {dev=7, ino=1, mode=S_IFIFO|0o600, nlink=1, uid=0, gid=0, rdev=0, size=0, blksize=4096, blocks=0, atime=2021-11-02 13:13:57.387645609 -0700 PDT, mtime=2021-11-02 13:13:57.255646695 -0700 PDT, ctime=2021-11-02 13:13:57.255646695 -0700 PDT}) = 0 (0x0) (16.039µs)
I1102 13:13:57.395087  1048149 strace.go:591] [   5:   6] java E ioctl(0x0 host:[1], 0x541b, 0x7fc23b7cefac)
I1102 13:13:57.395112  1048149 strace.go:629] [   5:   6] java X ioctl(0x0 host:[1], 0x541b, 0x7fc23b7cefac) = 0 (0x0) (6.916µs)   ===> IOCTL SUCCEEDED!! CODE TAKES A DIFFERENT PATH.
I1102 13:13:57.395362  1048149 strace.go:591] [   5:   6] java E lseek(0x4, 0xa152fc, 0x0)
I1102 13:13:57.395417  1048149 strace.go:629] [   5:   6] java X lseek(0x4, 0xa152fc, 0x0) = 10572540 (0xa152fc) (1.88µs)
```
