### ISSUE TITLE
'an illegal memory access was encountered' on T4 GPU past a certain level of GPU mem allocation 

### ISSUE THREAD

**Issue by thundergolfer** [google/gvisor#9176]
### Description

gVisor is returning this error at only `1795MiB / 15360MiB` memory usage on a T4 GPU (as reported by nvidia-smi), when our `runc` runtime completes successfully: 

```
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
```

I have tried to reproduce this on a A10G GPU and cannot. On the A10G GPU I hit an expected out-of-memory error when progressively increasing memory allocation.

This bug was first encountered in our production cluster which does not use `docker`.

### Steps to reproduce

These reproduction steps were run on a custom AMI built on Ubuntu 20.04. The AWS instance type is `g4dn.2xlarge`

**1. Install gvisor**

```bash
ARCH="x86_64"  # all workers are x86
URL="https://storage.googleapis.com/gvisor/releases/master/latest/${ARCH}"
wget -nc "${URL}/runsc" "${URL}/runsc.sha512"
chmod +x runsc
cp runsc /usr/local/bin/runsc
sudo /usr/local/bin/runsc install
sudo systemctl reload docker
```

**2. Add GPU enabling gvisor options**

In `/etc/docker/daemon.json`:

```json
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        },
        "runsc": {
            "path": "/usr/local/bin/runsc",
	    "runtimeArgs": ["--nvproxy", "--nvproxy-docker", "-debug-log=/tmp/runsc/", "-debug", "-strace"]

        }
    }
}
```

then run `sudo systemctl reload docker` 

**3. Run the reproducing PyTorch application**

```Dockerfile
# Dockerfile
FROM python:3.9.15-slim-bullseye

RUN pip install torch numpy
COPY <<EOF repro.py
import torch
print(torch.__version__)
torch.set_default_tensor_type(torch.DoubleTensor)
# Increase size of `n`, increasing memory usage, until 'illegal access' seen
# 4992 works for me, 4993 fails
n = 4993
print(f"matrix size: {n} x {n}")
assert torch.cuda.is_available(), "cuda not available"
M = torch.rand((n, n)).to(torch.device("cuda"))
N = torch.linalg.inv(M)
I = torch.eye(n).to(torch.device("cuda"))
R = torch.matmul(M, N) - I
threshold = 0.5
mean = torch.mean(torch.abs(R))
print(mean)
assert mean < threshold, f"Mean of matrix {mean} exceeded thresold of {threshold}."
EOF

ENTRYPOINT ["python3", "repro.py"]
```

then

```bash
docker build . -f Dockerfile -t repro-illegal-mem-access
```

then

```bash
sudo docker run --gpus all --runtime=runsc repro-illegal-mem-access
2.0.1+cu117
matrix size: 4993 x 4993
Traceback (most recent call last):
  File "//repro.py", line 15, in <module>
    print(mean)
  File "/usr/local/lib/python3.9/site-packages/torch/_tensor.py", line 426, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/usr/local/lib/python3.9/site-packages/torch/_tensor_str.py", line 636, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/usr/local/lib/python3.9/site-packages/torch/_tensor_str.py", line 567, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/usr/local/lib/python3.9/site-packages/torch/_tensor_str.py", line 328, in _tensor_str
    return _tensor_str_with_formatter(self, indent, summarize, formatter)
  File "/usr/local/lib/python3.9/site-packages/torch/_tensor_str.py", line 254, in _tensor_str_with_formatter
    return _scalar_str(self, formatter1, formatter2)
  File "/usr/local/lib/python3.9/site-packages/torch/_tensor_str.py", line 205, in _scalar_str
    return formatter1.format(self.item())
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### runsc version

```shell
runsc version release-20230710.0-22-gf5049f6885ca
spec: 1.1.0-rc.1
```
```


### docker version (if using docker)

```shell
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:50:57 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.4
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.5
  Git commit:       4ffc614
  Built:            Fri Jul  7 14:50:57 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Whereas with just the default Docker runtime:

```
ubuntu@ip-172-31-73-139:~$ sudo docker run --gpus all repro-illegal-mem-access
2.0.1+cu117
matrix size: 4993 x 4993
tensor(1.9216e-12, device='cuda:0')
```

### uname

`Linux ip-172-31-73-139 5.13.0-1029-aws #32~20.04.1-Ubuntu SMP Thu Jun 9 13:03:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### runsc debug logs (if available)

[runsc.log.20230714-213425.140959.create.txt](https://github.com/google/gvisor/files/12054101/runsc.log.20230714-213425.140959.create.txt)
[runsc.log.20230714-213425.464958.start.txt](https://github.com/google/gvisor/files/12054102/runsc.log.20230714-213425.464958.start.txt)
[runsc.log.20230714-213435.184722.delete.txt](https://github.com/google/gvisor/files/12054103/runsc.log.20230714-213435.184722.delete.txt)
[runsc.log.20230714-213425.259718.gofer.txt](https://github.com/google/gvisor/files/12054104/runsc.log.20230714-213425.259718.gofer.txt)
[runsc.log.20230714-213435.153023.delete.txt](https://github.com/google/gvisor/files/12054105/runsc.log.20230714-213435.153023.delete.txt)
[runsc.log.20230714-213425.264420.boot.txt](https://github.com/google/gvisor/files/12054106/runsc.log.20230714-213425.264420.boot.txt)

**Comment by nixprime** [comment]
Thanks for the detailed report and repro instructions!
